package com.sertek.table;

/**
 * SO..C60 <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:30.58<br>
 * 
 */
public class C60 extends BaseTable {

	/**
	 * SO..C60.CRTID 
	 */
	private String crtid = "";

	/**
	 * SO..C60.SYS 
	 */
	private String sys = "";

	/**
	 * SO..C60.SYSKD 
	 */
	private String syskd = "";

	/**
	 * SO..C60.S_KD 
	 */
	private String s_kd = "";

	/**
	 * SO..C60.C_NO 
	 */
	private String c_no = "";

	/**
	 * SO..C60.C_DT 
	 */
	private String c_dt = "";

	/**
	 * SO..C60.C_TM 
	 */
	private String c_tm = "";

	/**
	 * SO..C60.DOC_NO 
	 */
	private String doc_no = "";

	/**
	 * SO..C60.ODOC_NO 
	 */
	private String odoc_no = "";

	/**
	 * SO..C60.CRMYY 
	 */
	private String crmyy = "";

	/**
	 * SO..C60.CRMID 
	 */
	private String crmid = "";

	/**
	 * SO..C60.CRMNO 
	 */
	private String crmno = "";

	/**
	 * SO..C60.DPT 
	 */
	private String dpt = "";

	/**
	 * SO..C60.RCVDT 
	 */
	private String rcvdt = "";

	/**
	 * SO..C60.RCVTM 
	 */
	private String rcvtm = "";

	/**
	 * SO..C60.CRMDT 
	 */
	private String crmdt = "";

	/**
	 * SO..C60.PEDT 
	 */
	private String pedt = "";

	/**
	 * SO..C60.C_STATUS 
	 */
	private String c_status = "";

	/**
	 * SO..C60.P_STATUS 
	 */
	private String p_status = "";

	/**
	 * SO..C60.T_STATUS 
	 */
	private String t_status = "";

	/**
	 * SO..C60.USRID 
	 */
	private String usrid = "";

	/**
	 * SO..C60.USRNM 
	 */
	private String usrnm = "";

	/**
	 * SO..C60.IDAPTNM 
	 */
	private String idaptnm = "";

	/**
	 * SO..C60.IDNM 
	 */
	private String idnm = "";

	/**
	 * SO..C60.CRT_APV 
	 */
	private String crt_apv = "";

	/**
	 * SO..C60.DLV_DTM 
	 */
	private String def_apv = "";
	

	private String tostatus = "";
	private String tocrtid = "";
	private String todoc_no = "";
	
	

	public String getTocrtid() {
		return tocrtid;
	}

	public void setTocrtid(String tocrtid) {
		this.tocrtid = tocrtid;
	}

	public String getTodoc_no() {
		return todoc_no;
	}

	public void setTodoc_no(String todoc_no) {
		this.todoc_no = todoc_no;
	}

	public String getTostatus() {
		return tostatus;
	}

	public void setTostatus(String tostatus) {
		this.tostatus = tostatus;
	}

	public String getDef_apv() {
		return def_apv;
	}

	public void setDef_apv(String def_apv) {
		this.def_apv = def_apv;
	}

	/**
	 * @return SO..C60.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..C60.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

	/**
	 * @return SO..C60.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..C60.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..C60.SYSKD 
	 */
	public String getSyskd() {
		return syskd;
	}

	/**
	 * @param syskd SO..C60.SYSKD 
	 */
	public void setSyskd(String syskd) {
		this.syskd = syskd;
	}

	/**
	 * @return SO..C60.S_KD 
	 */
	public String getS_kd() {
		return s_kd;
	}

	/**
	 * @param s_kd SO..C60.S_KD 
	 */
	public void setS_kd(String s_kd) {
		this.s_kd = s_kd;
	}

	/**
	 * @return SO..C60.C_NO 
	 */
	public String getC_no() {
		return c_no;
	}

	/**
	 * @param c_no SO..C60.C_NO 
	 */
	public void setC_no(String c_no) {
		this.c_no = c_no;
	}

	/**
	 * @return SO..C60.C_DT 
	 */
	public String getC_dt() {
		return c_dt;
	}

	/**
	 * @param c_dt SO..C60.C_DT 
	 */
	public void setC_dt(String c_dt) {
		this.c_dt = c_dt;
	}

	/**
	 * @return SO..C60.C_TM 
	 */
	public String getC_tm() {
		return c_tm;
	}

	/**
	 * @param c_tm SO..C60.C_TM 
	 */
	public void setC_tm(String c_tm) {
		this.c_tm = c_tm;
	}

	/**
	 * @return SO..C60.DOC_NO 
	 */
	public String getDoc_no() {
		return doc_no;
	}

	/**
	 * @param doc_no SO..C60.DOC_NO 
	 */
	public void setDoc_no(String doc_no) {
		this.doc_no = doc_no;
	}

	/**
	 * @return SO..C60.ODOC_NO 
	 */
	public String getOdoc_no() {
		return odoc_no;
	}

	/**
	 * @param odoc_no SO..C60.ODOC_NO 
	 */
	public void setOdoc_no(String odoc_no) {
		this.odoc_no = odoc_no;
	}

	/**
	 * @return SO..C60.CRMYY 
	 */
	public String getCrmyy() {
		return crmyy;
	}

	/**
	 * @param crmyy SO..C60.CRMYY 
	 */
	public void setCrmyy(String crmyy) {
		this.crmyy = crmyy;
	}

	/**
	 * @return SO..C60.CRMID 
	 */
	public String getCrmid() {
		return crmid;
	}

	/**
	 * @param crmid SO..C60.CRMID 
	 */
	public void setCrmid(String crmid) {
		this.crmid = crmid;
	}

	/**
	 * @return SO..C60.CRMNO 
	 */
	public String getCrmno() {
		return crmno;
	}

	/**
	 * @param crmno SO..C60.CRMNO 
	 */
	public void setCrmno(String crmno) {
		this.crmno = crmno;
	}

	/**
	 * @return SO..C60.DPT 
	 */
	public String getDpt() {
		return dpt;
	}

	/**
	 * @param dpt SO..C60.DPT 
	 */
	public void setDpt(String dpt) {
		this.dpt = dpt;
	}

	/**
	 * @return SO..C60.RCVDT 
	 */
	public String getRcvdt() {
		return rcvdt;
	}

	/**
	 * @param rcvdt SO..C60.RCVDT 
	 */
	public void setRcvdt(String rcvdt) {
		this.rcvdt = rcvdt;
	}

	/**
	 * @return SO..C60.RCVTM 
	 */
	public String getRcvtm() {
		return rcvtm;
	}

	/**
	 * @param rcvtm SO..C60.RCVTM 
	 */
	public void setRcvtm(String rcvtm) {
		this.rcvtm = rcvtm;
	}

	/**
	 * @return SO..C60.CRMDT 
	 */
	public String getCrmdt() {
		return crmdt;
	}

	/**
	 * @param crmdt SO..C60.CRMDT 
	 */
	public void setCrmdt(String crmdt) {
		this.crmdt = crmdt;
	}

	/**
	 * @return SO..C60.PEDT 
	 */
	public String getPedt() {
		return pedt;
	}

	/**
	 * @param pedt SO..C60.PEDT 
	 */
	public void setPedt(String pedt) {
		this.pedt = pedt;
	}

	/**
	 * @return SO..C60.C_STATUS 
	 */
	public String getC_status() {
		return c_status;
	}

	/**
	 * @param c_status SO..C60.C_STATUS 
	 */
	public void setC_status(String c_status) {
		this.c_status = c_status;
	}

	/**
	 * @return SO..C60.P_STATUS 
	 */
	public String getP_status() {
		return p_status;
	}

	/**
	 * @param p_status SO..C60.P_STATUS 
	 */
	public void setP_status(String p_status) {
		this.p_status = p_status;
	}

	/**
	 * @return SO..C60.T_STATUS 
	 */
	public String getT_status() {
		return t_status;
	}

	/**
	 * @param t_status SO..C60.T_STATUS 
	 */
	public void setT_status(String t_status) {
		this.t_status = t_status;
	}

	/**
	 * @return SO..C60.USRID 
	 */
	public String getUsrid() {
		return usrid;
	}

	/**
	 * @param usrid SO..C60.USRID 
	 */
	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

	/**
	 * @return SO..C60.USRNM 
	 */
	public String getUsrnm() {
		return usrnm;
	}

	/**
	 * @param usrnm SO..C60.USRNM 
	 */
	public void setUsrnm(String usrnm) {
		this.usrnm = usrnm;
	}

	/**
	 * @return SO..C60.IDAPTNM 
	 */
	public String getIdaptnm() {
		return idaptnm;
	}

	/**
	 * @param idaptnm SO..C60.IDAPTNM 
	 */
	public void setIdaptnm(String idaptnm) {
		this.idaptnm = idaptnm;
	}

	/**
	 * @return SO..C60.IDNM 
	 */
	public String getIdnm() {
		return idnm;
	}

	/**
	 * @param idnm SO..C60.IDNM 
	 */
	public void setIdnm(String idnm) {
		this.idnm = idnm;
	}
	private String dlv_dtm = "";

	public String getCrt_apv() {
		return crt_apv;
	}

	public void setCrt_apv(String crt_apv) {
		this.crt_apv = crt_apv;
	}

	public String getDlv_dtm() {
		return dlv_dtm;
	}

	public void setDlv_dtm(String dlv_dtm) {
		this.dlv_dtm = dlv_dtm;
	}

}
