package com.sertek.table;

/**
 * SO..C60_DOC <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:30.676<br>
 * 
 */
public class C60_DOC extends BaseTable {

	/**
	 * SO..C60_DOC.CRTID 
	 */
	private String crtid = "";

	/**
	 * SO..C60_DOC.SYS 
	 */
	private String sys = "";

	/**
	 * SO..C60_DOC.C_NO 
	 */
	private String c_no = "";

	/**
	 * SO..C60_DOC.S_SEQ 
	 */
	private String s_seq = "";

	/**
	 * SO..C60_DOC.S_DOC 
	 */
	private String s_doc = "";

	/**
	 * SO..C60_DOC.RMK 
	 */
	private String rmk = "";

	/**
	 * SO..C60_DOC.S_STATUS 
	 */
	private String s_status = "";

	/**
	 * SO..C60_DOC.S_UPDT 
	 */
	private String s_updt = "";

	/**
	 * SO..C60_DOC.S_UPTM 
	 */
	private String s_uptm = "";

	/**
	 * SO..C60_DOC.USRID 
	 */
	private String usrid = "";

	/**
	 * @return SO..C60_DOC.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..C60_DOC.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

	/**
	 * @return SO..C60_DOC.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..C60_DOC.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..C60_DOC.C_NO 
	 */
	public String getC_no() {
		return c_no;
	}

	/**
	 * @param c_no SO..C60_DOC.C_NO 
	 */
	public void setC_no(String c_no) {
		this.c_no = c_no;
	}

	/**
	 * @return SO..C60_DOC.S_SEQ 
	 */
	public String getS_seq() {
		return s_seq;
	}

	/**
	 * @param s_seq SO..C60_DOC.S_SEQ 
	 */
	public void setS_seq(String s_seq) {
		this.s_seq = s_seq;
	}

	/**
	 * @return SO..C60_DOC.S_DOC 
	 */
	public String getS_doc() {
		return s_doc;
	}

	/**
	 * @param s_doc SO..C60_DOC.S_DOC 
	 */
	public void setS_doc(String s_doc) {
		this.s_doc = s_doc;
	}

	/**
	 * @return SO..C60_DOC.RMK 
	 */
	public String getRmk() {
		return rmk;
	}

	/**
	 * @param rmk SO..C60_DOC.RMK 
	 */
	public void setRmk(String rmk) {
		this.rmk = rmk;
	}

	/**
	 * @return SO..C60_DOC.S_STATUS 
	 */
	public String getS_status() {
		return s_status;
	}

	/**
	 * @param s_status SO..C60_DOC.S_STATUS 
	 */
	public void setS_status(String s_status) {
		this.s_status = s_status;
	}

	/**
	 * @return SO..C60_DOC.S_UPDT 
	 */
	public String getS_updt() {
		return s_updt;
	}

	/**
	 * @param s_updt SO..C60_DOC.S_UPDT 
	 */
	public void setS_updt(String s_updt) {
		this.s_updt = s_updt;
	}

	/**
	 * @return SO..C60_DOC.S_UPTM 
	 */
	public String getS_uptm() {
		return s_uptm;
	}

	/**
	 * @param s_uptm SO..C60_DOC.S_UPTM 
	 */
	public void setS_uptm(String s_uptm) {
		this.s_uptm = s_uptm;
	}

	/**
	 * @return SO..C60_DOC.USRID 
	 */
	public String getUsrid() {
		return usrid;
	}

	/**
	 * @param usrid SO..C60_DOC.USRID 
	 */
	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

}
