package com.sertek.table;

/**
 * SO..C60_ATT <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:30.628<br>
 * 
 */
public class C60_ATT extends BaseTable {

	/**
	 * SO..C60_ATT.CRTID 
	 */
	private String crtid = "";

	/**
	 * SO..C60_ATT.SYS 
	 */
	private String sys = "";

	/**
	 * SO..C60_ATT.C_NO 
	 */
	private String c_no = "";

	/**
	 * SO..C60_ATT.S_SEQ 
	 */
	private String s_seq = "";

	/**
	 * SO..C60_ATT.S_FTYPE 
	 */
	private String s_ftype = "";

	/**
	 * SO..C60_ATT.S_FILE 
	 */
	private String s_file = "";

	/**
	 * SO..C60_ATT.S_FILESEQ 
	 */
	private String s_fileseq = "";

	/**
	 * SO..C60_ATT.S_FILENM 
	 */
	private String s_filenm = "";

	/**
	 * SO..C60_ATT.S_FILEDS 
	 */
	private String s_fileds = "";

	/**
	 * SO..C60_ATT.S_FILESZ 
	 */
	private String s_filesz = "";

	/**
	 * SO..C60_ATT.S_UPDT 
	 */
	private String s_updt = "";

	/**
	 * SO..C60_ATT.S_UPTM 
	 */
	private String s_uptm = "";

	/**
	 * SO..C60_ATT.USRID 
	 */
	private String usrid = "";

	/**
	 * SO..C60_ATT.S_MD5 
	 */
	private String s_md5 = "";
	
	/**
	 * SO..C60_ATT.S_SHA2 
	 */
	private String s_sha2 = "";

	/**
	 * SO..C60_ATT.S_OPSN 
	 */
	private String s_opsn = "";

	/**
	 * SO..C60_ATT.S_OPSN 
	 */
	private String s_ip = "";

	public String getS_ip() {
		return s_ip;
	}

	public void setS_ip(String s_ip) {
		this.s_ip = s_ip;
	}

	/**
	 * @return SO..C60_ATT.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..C60_ATT.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

	/**
	 * @return SO..C60_ATT.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..C60_ATT.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..C60_ATT.C_NO 
	 */
	public String getC_no() {
		return c_no;
	}

	/**
	 * @param c_no SO..C60_ATT.C_NO 
	 */
	public void setC_no(String c_no) {
		this.c_no = c_no;
	}

	/**
	 * @return SO..C60_ATT.S_SEQ 
	 */
	public String getS_seq() {
		return s_seq;
	}

	/**
	 * @param s_seq SO..C60_ATT.S_SEQ 
	 */
	public void setS_seq(String s_seq) {
		this.s_seq = s_seq;
	}

	/**
	 * @return SO..C60_ATT.S_FTYPE 
	 */
	public String getS_ftype() {
		return s_ftype;
	}

	/**
	 * @param s_ftype SO..C60_ATT.S_FTYPE 
	 */
	public void setS_ftype(String s_ftype) {
		this.s_ftype = s_ftype;
	}

	/**
	 * @return SO..C60_ATT.S_FILE 
	 */
	public String getS_file() {
		return s_file;
	}

	/**
	 * @param s_file SO..C60_ATT.S_FILE 
	 */
	public void setS_file(String s_file) {
		this.s_file = s_file;
	}

	/**
	 * @return SO..C60_ATT.S_FILESEQ 
	 */
	public String getS_fileseq() {
		return s_fileseq;
	}

	/**
	 * @param s_fileseq SO..C60_ATT.S_FILESEQ 
	 */
	public void setS_fileseq(String s_fileseq) {
		this.s_fileseq = s_fileseq;
	}

	/**
	 * @return SO..C60_ATT.S_FILENM 
	 */
	public String getS_filenm() {
		return s_filenm;
	}

	/**
	 * @param s_filenm SO..C60_ATT.S_FILENM 
	 */
	public void setS_filenm(String s_filenm) {
		this.s_filenm = s_filenm;
	}

	/**
	 * @return SO..C60_ATT.S_FILEDS 
	 */
	public String getS_fileds() {
		return s_fileds;
	}

	/**
	 * @param s_fileds SO..C60_ATT.S_FILEDS 
	 */
	public void setS_fileds(String s_fileds) {
		this.s_fileds = s_fileds;
	}

	/**
	 * @return SO..C60_ATT.S_FILESZ 
	 */
	public String getS_filesz() {
		return s_filesz;
	}

	/**
	 * @param s_filesz SO..C60_ATT.S_FILESZ 
	 */
	public void setS_filesz(String s_filesz) {
		this.s_filesz = s_filesz;
	}

	/**
	 * @return SO..C60_ATT.S_UPDT 
	 */
	public String getS_updt() {
		return s_updt;
	}

	/**
	 * @param s_updt SO..C60_ATT.S_UPDT 
	 */
	public void setS_updt(String s_updt) {
		this.s_updt = s_updt;
	}

	/**
	 * @return SO..C60_ATT.S_UPTM 
	 */
	public String getS_uptm() {
		return s_uptm;
	}

	/**
	 * @param s_uptm SO..C60_ATT.S_UPTM 
	 */
	public void setS_uptm(String s_uptm) {
		this.s_uptm = s_uptm;
	}

	/**
	 * @return SO..C60_ATT.USRID 
	 */
	public String getUsrid() {
		return usrid;
	}

	/**
	 * @param usrid SO..C60_ATT.USRID 
	 */
	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

	/**
	 * @return SO..C60_ATT.S_MD5 
	 */
	public String getS_md5() {
		return s_md5;
	}

	/**
	 * @param s_md5 SO..C60_ATT.S_MD5 
	 */
	public void setS_md5(String s_md5) {
		this.s_md5 = s_md5;
	}

	/**
	 * @param s_md5 SO..C60_ATT.S_SHA2 
	 */
	public void setS_sha2(String S_sha2) {
		this.s_sha2 = S_sha2;
	}
	
	/**
	 * @return SO..C60_ATT.S_SHA2 
	 */
	public String getS_sha2() {
		return s_sha2;
	}

	
	/**
	 * @return SO..C60_ATT.S_OPSN 
	 */
	public String getS_opsn() {
		return s_opsn;
	}

	/**
	 * @param s_opsn SO..C60_ATT.S_OPSN 
	 */
	public void setS_opsn(String s_opsn) {
		this.s_opsn = s_opsn;
	}

}
