package com.sertek.table;

/**
 * SO..C60_ADD <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:30.612<br>
 * 
 */
public class C60_ADD extends BaseTable {

	/**
	 * SO..C60_ADD.CRTID 
	 */
	private String crtid = "";

	/**
	 * SO..C60_ADD.SYS 
	 */
	private String sys = "";

	/**
	 * SO..C60_ADD.C_NO 
	 */
	private String c_no = "";

	/**
	 * SO..C60_ADD.A_DT 
	 */
	private String a_dt = "";

	/**
	 * SO..C60_ADD.A_TM 
	 */
	private String a_tm = "";

	/**
	 * SO..C60_ADD.DOC_NO 
	 */
	private String doc_no = "";

	/**
	 * SO..C60_ADD.CRMYY 
	 */
	private String crmyy = "";

	/**
	 * SO..C60_ADD.CRMID 
	 */
	private String crmid = "";

	/**
	 * SO..C60_ADD.CRMNO 
	 */
	private String crmno = "";

	/**
	 * SO..C60_ADD.DPT 
	 */
	private String dpt = "";

	/**
	 * SO..C60_ADD.USRNM 
	 */
	private String usrnm = "";

	/**
	 * SO..C60_ADD.USRID 
	 */
	private String usrid = "";

	/**
	 * SO..C60_ADD.YESREAD 
	 */
	private String yesread = "";

	/**
	 * SO..C60_ADD.S61CLNM 
	 */
	private String s61clnm = "";

	/**
	 * @return SO..C60_ADD.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..C60_ADD.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

	/**
	 * @return SO..C60_ADD.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..C60_ADD.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..C60_ADD.C_NO 
	 */
	public String getC_no() {
		return c_no;
	}

	/**
	 * @param c_no SO..C60_ADD.C_NO 
	 */
	public void setC_no(String c_no) {
		this.c_no = c_no;
	}

	/**
	 * @return SO..C60_ADD.A_DT 
	 */
	public String getA_dt() {
		return a_dt;
	}

	/**
	 * @param a_dt SO..C60_ADD.A_DT 
	 */
	public void setA_dt(String a_dt) {
		this.a_dt = a_dt;
	}

	/**
	 * @return SO..C60_ADD.A_TM 
	 */
	public String getA_tm() {
		return a_tm;
	}

	/**
	 * @param a_tm SO..C60_ADD.A_TM 
	 */
	public void setA_tm(String a_tm) {
		this.a_tm = a_tm;
	}

	/**
	 * @return SO..C60_ADD.DOC_NO 
	 */
	public String getDoc_no() {
		return doc_no;
	}

	/**
	 * @param doc_no SO..C60_ADD.DOC_NO 
	 */
	public void setDoc_no(String doc_no) {
		this.doc_no = doc_no;
	}

	/**
	 * @return SO..C60_ADD.CRMYY 
	 */
	public String getCrmyy() {
		return crmyy;
	}

	/**
	 * @param crmyy SO..C60_ADD.CRMYY 
	 */
	public void setCrmyy(String crmyy) {
		this.crmyy = crmyy;
	}

	/**
	 * @return SO..C60_ADD.CRMID 
	 */
	public String getCrmid() {
		return crmid;
	}

	/**
	 * @param crmid SO..C60_ADD.CRMID 
	 */
	public void setCrmid(String crmid) {
		this.crmid = crmid;
	}

	/**
	 * @return SO..C60_ADD.CRMNO 
	 */
	public String getCrmno() {
		return crmno;
	}

	/**
	 * @param crmno SO..C60_ADD.CRMNO 
	 */
	public void setCrmno(String crmno) {
		this.crmno = crmno;
	}

	/**
	 * @return SO..C60_ADD.DPT 
	 */
	public String getDpt() {
		return dpt;
	}

	/**
	 * @param dpt SO..C60_ADD.DPT 
	 */
	public void setDpt(String dpt) {
		this.dpt = dpt;
	}

	/**
	 * @return SO..C60_ADD.USRNM 
	 */
	public String getUsrnm() {
		return usrnm;
	}

	/**
	 * @param usrnm SO..C60_ADD.USRNM 
	 */
	public void setUsrnm(String usrnm) {
		this.usrnm = usrnm;
	}

	/**
	 * @return SO..C60_ADD.USRID 
	 */
	public String getUsrid() {
		return usrid;
	}

	/**
	 * @param usrid SO..C60_ADD.USRID 
	 */
	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

	/**
	 * @return SO..C60_ADD.YESREAD 
	 */
	public String getYesread() {
		return yesread;
	}

	/**
	 * @param yesread SO..C60_ADD.YESREAD 
	 */
	public void setYesread(String yesread) {
		this.yesread = yesread;
	}

	/**
	 * @return SO..C60_ADD.S61CLNM 
	 */
	public String getS61clnm() {
		return s61clnm;
	}

	/**
	 * @param s61clnm SO..C60_ADD.S61CLNM 
	 */
	public void setS61clnm(String s61clnm) {
		this.s61clnm = s61clnm;
	}

}
