package com.sertek.table;

/**
 * SO..C60_PAY <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:30.707<br>
 * 
 */
public class C60_PAY extends BaseTable {

	/**
	 * SO..C60_PAY.CRTID 
	 */
	private String crtid = "";

	/**
	 * SO..C60_PAY.SYS 
	 */
	private String sys = "";

	/**
	 * SO..C60_PAY.DOC_NO 
	 */
	private String doc_no = "";

	/**
	 * SO..C60_PAY.P_AMT 
	 */
	private String p_amt = "";

	/**
	 * SO..C60_PAY.P_PAYID 
	 */
	private String p_payid = "";

	/**
	 * SO..C60_PAY.P_DT 
	 */
	private String p_dt = "";

	/**
	 * SO..C60_PAY.P_TM 
	 */
	private String p_tm = "";

	/**
	 * SO..C60_PAY.COMDT 
	 */
	private String comdt = "";

	/**
	 * SO..C60_PAY.COMTM 
	 */
	private String comtm = "";

	/**
	 * SO..C60_PAY.P_STATUS 
	 */
	private String p_status = "";

	/**
	 * SO..C60_PAY.BANKID 
	 */
	private String bankid = "";

	/**
	 * SO..C60_PAY.BANKNAME 
	 */
	private String bankname = "";

	/**
	 * SO..C60_PAY.BANKACC 
	 */
	private String bankacc = "";

	/**
	 * SO..C60_PAY.ACCTYPE 
	 */
	private String acctype = "";

	/**
	 * SO..C60_PAY.TXNID 
	 */
	private String txnid = "";

	/**
	 * SO..C60_PAY.CODE 
	 */
	private String code = "";

	/**
	 * SO..C60_PAY.PAYTXNFEE 
	 */
	private String paytxnfee = "";

	/**
	 * SO..C60_PAY.BARCODE1 
	 */
	private String barcode1 = "";

	/**
	 * SO..C60_PAY.BARCODE2 
	 */
	private String barcode2 = "";

	/**
	 * SO..C60_PAY.BARCODE3 
	 */
	private String barcode3 = "";
	private String pname = "";

	public String getPname() {
		return pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getBarcode3() {
		return barcode3;
	}

	public void setBarcode3(String barcode3) {
		this.barcode3 = barcode3;
	}

	/**
	 * SO..C60_PAY.RMK 
	 */
	private String rmk = "";

	/**
	 * SO..C60_PAY.CTYPE 
	 */
	private String ctype = "";

	/**
	 * SO..C60_PAY.TRNTYPE 
	 */
	private String trntype = "";

	/**
	 * SO..C60_PAY.EP_YY 
	 */
	private String ep_yy = "";

	/**
	 * SO..C60_PAY.EP_ID 
	 */
	private String ep_id = "";

	/**
	 * SO..C60_PAY.EP_NO 
	 */
	private String ep_no = "";

	/**
	 * SO..C60_PAY.CDDT 
	 */
	private String cddt = "";

	/**
	 * @return SO..C60_PAY.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..C60_PAY.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

	/**
	 * @return SO..C60_PAY.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..C60_PAY.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..C60_PAY.DOC_NO 
	 */
	public String getDoc_no() {
		return doc_no;
	}

	/**
	 * @param doc_no SO..C60_PAY.DOC_NO 
	 */
	public void setDoc_no(String doc_no) {
		this.doc_no = doc_no;
	}

	/**
	 * @return SO..C60_PAY.P_AMT 
	 */
	public String getP_amt() {
		return p_amt;
	}

	/**
	 * @param p_amt SO..C60_PAY.P_AMT 
	 */
	public void setP_amt(String p_amt) {
		this.p_amt = p_amt;
	}

	/**
	 * @return SO..C60_PAY.P_PAYID 
	 */
	public String getP_payid() {
		return p_payid;
	}

	/**
	 * @param p_payid SO..C60_PAY.P_PAYID 
	 */
	public void setP_payid(String p_payid) {
		this.p_payid = p_payid;
	}

	/**
	 * @return SO..C60_PAY.P_DT 
	 */
	public String getP_dt() {
		return p_dt;
	}

	/**
	 * @param p_dt SO..C60_PAY.P_DT 
	 */
	public void setP_dt(String p_dt) {
		this.p_dt = p_dt;
	}

	/**
	 * @return SO..C60_PAY.P_TM 
	 */
	public String getP_tm() {
		return p_tm;
	}

	/**
	 * @param p_tm SO..C60_PAY.P_TM 
	 */
	public void setP_tm(String p_tm) {
		this.p_tm = p_tm;
	}

	/**
	 * @return SO..C60_PAY.COMDT 
	 */
	public String getComdt() {
		return comdt;
	}

	/**
	 * @param comdt SO..C60_PAY.COMDT 
	 */
	public void setComdt(String comdt) {
		this.comdt = comdt;
	}

	/**
	 * @return SO..C60_PAY.COMTM 
	 */
	public String getComtm() {
		return comtm;
	}

	/**
	 * @param comtm SO..C60_PAY.COMTM 
	 */
	public void setComtm(String comtm) {
		this.comtm = comtm;
	}

	/**
	 * @return SO..C60_PAY.P_STATUS 
	 */
	public String getP_status() {
		return p_status;
	}

	/**
	 * @param p_status SO..C60_PAY.P_STATUS 
	 */
	public void setP_status(String p_status) {
		this.p_status = p_status;
	}

	/**
	 * @return SO..C60_PAY.BANKID 
	 */
	public String getBankid() {
		return bankid;
	}

	/**
	 * @param bankid SO..C60_PAY.BANKID 
	 */
	public void setBankid(String bankid) {
		this.bankid = bankid;
	}

	/**
	 * @return SO..C60_PAY.BANKNAME 
	 */
	public String getBankname() {
		return bankname;
	}

	/**
	 * @param bankname SO..C60_PAY.BANKNAME 
	 */
	public void setBankname(String bankname) {
		this.bankname = bankname;
	}

	/**
	 * @return SO..C60_PAY.BANKACC 
	 */
	public String getBankacc() {
		return bankacc;
	}

	/**
	 * @param bankacc SO..C60_PAY.BANKACC 
	 */
	public void setBankacc(String bankacc) {
		this.bankacc = bankacc;
	}

	/**
	 * @return SO..C60_PAY.ACCTYPE 
	 */
	public String getAcctype() {
		return acctype;
	}

	/**
	 * @param acctype SO..C60_PAY.ACCTYPE 
	 */
	public void setAcctype(String acctype) {
		this.acctype = acctype;
	}

	/**
	 * @return SO..C60_PAY.TXNID 
	 */
	public String getTxnid() {
		return txnid;
	}

	/**
	 * @param txnid SO..C60_PAY.TXNID 
	 */
	public void setTxnid(String txnid) {
		this.txnid = txnid;
	}

	/**
	 * @return SO..C60_PAY.CODE 
	 */
	public String getCode() {
		return code;
	}

	/**
	 * @param code SO..C60_PAY.CODE 
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * @return SO..C60_PAY.PAYTXNFEE 
	 */
	public String getPaytxnfee() {
		return paytxnfee;
	}

	/**
	 * @param paytxnfee SO..C60_PAY.PAYTXNFEE 
	 */
	public void setPaytxnfee(String paytxnfee) {
		this.paytxnfee = paytxnfee;
	}

	/**
	 * @return SO..C60_PAY.BARCODE1 
	 */
	public String getBarcode1() {
		return barcode1;
	}

	/**
	 * @param barcode1 SO..C60_PAY.BARCODE1 
	 */
	public void setBarcode1(String barcode1) {
		this.barcode1 = barcode1;
	}

	/**
	 * @return SO..C60_PAY.BARCODE2 
	 */
	public String getBarcode2() {
		return barcode2;
	}

	/**
	 * @param barcode2 SO..C60_PAY.BARCODE2 
	 */
	public void setBarcode2(String barcode2) {
		this.barcode2 = barcode2;
	}

	/**
	 * @return SO..C60_PAY.RMK 
	 */
	public String getRmk() {
		return rmk;
	}

	/**
	 * @param rmk SO..C60_PAY.RMK 
	 */
	public void setRmk(String rmk) {
		this.rmk = rmk;
	}

	/**
	 * @return SO..C60_PAY.CTYPE 
	 */
	public String getCtype() {
		return ctype;
	}

	/**
	 * @param ctype SO..C60_PAY.CTYPE 
	 */
	public void setCtype(String ctype) {
		this.ctype = ctype;
	}

	/**
	 * @return SO..C60_PAY.TRNTYPE 
	 */
	public String getTrntype() {
		return trntype;
	}

	/**
	 * @param trntype SO..C60_PAY.TRNTYPE 
	 */
	public void setTrntype(String trntype) {
		this.trntype = trntype;
	}

	/**
	 * @return SO..C60_PAY.EP_YY 
	 */
	public String getEp_yy() {
		return ep_yy;
	}

	/**
	 * @param ep_yy SO..C60_PAY.EP_YY 
	 */
	public void setEp_yy(String ep_yy) {
		this.ep_yy = ep_yy;
	}

	/**
	 * @return SO..C60_PAY.EP_ID 
	 */
	public String getEp_id() {
		return ep_id;
	}

	/**
	 * @param ep_id SO..C60_PAY.EP_ID 
	 */
	public void setEp_id(String ep_id) {
		this.ep_id = ep_id;
	}

	/**
	 * @return SO..C60_PAY.EP_NO 
	 */
	public String getEp_no() {
		return ep_no;
	}

	/**
	 * @param ep_no SO..C60_PAY.EP_NO 
	 */
	public void setEp_no(String ep_no) {
		this.ep_no = ep_no;
	}

	/**
	 * @return SO..C60_PAY.CDDT 
	 */
	public String getCddt() {
		return cddt;
	}

	/**
	 * @param cddt SO..C60_PAY.CDDT 
	 */
	public void setCddt(String cddt) {
		this.cddt = cddt;
	}

}
