package com.sertek.table;

/**
 * SO..C60_WEB <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:30.738<br>
 * 
 */
public class C60_WEB extends BaseTable {

	/**
	 * SO..C60_WEB.CRTID 
	 */
	private String crtid = "";

	/**
	 * SO..C60_WEB.SYS 
	 */
	private String sys = "";

	/**
	 * SO..C60_WEB.C_NO 
	 */
	private String c_no = "";

	/**
	 * SO..C60_WEB.S_SEQ 
	 */
	private String s_seq = "";

	/**
	 * SO..C60_WEB.S_PRICE 
	 */
	private String s_price = "";

	/**
	 * SO..C60_WEB.S_CAUSE 
	 */
	private String s_cause = "";

	/**
	 * SO..C60_WEB.S_STMT 
	 */
	private String s_stmt = "";

	/**
	 * SO..C60_WEB.S_FACT 
	 */
	private String s_fact = "";

	/**
	 * SO..C60_WEB.S_EVD 
	 */
	private String s_evd = "";

	/**
	 * SO..C60_WEB.S_OPSN 
	 */
	private String s_opsn = "";

	/**
	 * SO..C60_WEB.S_PSN 
	 */
	private String s_psn = "";

	/**
	 * SO..C60_WEB.W_PSN 
	 */
	private String w_psn = "";

	/**
	 * SO..C60_WEB.S_UPDT 
	 */
	private String s_updt = "";

	/**
	 * SO..C60_WEB.S_UPTM 
	 */
	private String s_uptm = "";

	/**
	 * SO..C60_WEB.USRID 
	 */
	private String usrid = "";

	/**
	 * @return SO..C60_WEB.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..C60_WEB.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

	/**
	 * @return SO..C60_WEB.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..C60_WEB.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..C60_WEB.C_NO 
	 */
	public String getC_no() {
		return c_no;
	}

	/**
	 * @param c_no SO..C60_WEB.C_NO 
	 */
	public void setC_no(String c_no) {
		this.c_no = c_no;
	}

	/**
	 * @return SO..C60_WEB.S_SEQ 
	 */
	public String getS_seq() {
		return s_seq;
	}

	/**
	 * @param s_seq SO..C60_WEB.S_SEQ 
	 */
	public void setS_seq(String s_seq) {
		this.s_seq = s_seq;
	}

	/**
	 * @return SO..C60_WEB.S_PRICE 
	 */
	public String getS_price() {
		return s_price;
	}

	/**
	 * @param s_price SO..C60_WEB.S_PRICE 
	 */
	public void setS_price(String s_price) {
		this.s_price = s_price;
	}

	/**
	 * @return SO..C60_WEB.S_CAUSE 
	 */
	public String getS_cause() {
		return s_cause;
	}

	/**
	 * @param s_cause SO..C60_WEB.S_CAUSE 
	 */
	public void setS_cause(String s_cause) {
		this.s_cause = s_cause;
	}

	/**
	 * @return SO..C60_WEB.S_STMT 
	 */
	public String getS_stmt() {
		return s_stmt;
	}

	/**
	 * @param s_stmt SO..C60_WEB.S_STMT 
	 */
	public void setS_stmt(String s_stmt) {
		this.s_stmt = s_stmt;
	}

	/**
	 * @return SO..C60_WEB.S_FACT 
	 */
	public String getS_fact() {
		return s_fact;
	}

	/**
	 * @param s_fact SO..C60_WEB.S_FACT 
	 */
	public void setS_fact(String s_fact) {
		this.s_fact = s_fact;
	}

	/**
	 * @return SO..C60_WEB.S_EVD 
	 */
	public String getS_evd() {
		return s_evd;
	}

	/**
	 * @param s_evd SO..C60_WEB.S_EVD 
	 */
	public void setS_evd(String s_evd) {
		this.s_evd = s_evd;
	}

	/**
	 * @return SO..C60_WEB.S_OPSN 
	 */
	public String getS_opsn() {
		return s_opsn;
	}

	/**
	 * @param s_opsn SO..C60_WEB.S_OPSN 
	 */
	public void setS_opsn(String s_opsn) {
		this.s_opsn = s_opsn;
	}

	/**
	 * @return SO..C60_WEB.S_PSN 
	 */
	public String getS_psn() {
		return s_psn;
	}

	/**
	 * @param s_psn SO..C60_WEB.S_PSN 
	 */
	public void setS_psn(String s_psn) {
		this.s_psn = s_psn;
	}

	/**
	 * @return SO..C60_WEB.W_PSN 
	 */
	public String getW_psn() {
		return w_psn;
	}

	/**
	 * @param w_psn SO..C60_WEB.W_PSN 
	 */
	public void setW_psn(String w_psn) {
		this.w_psn = w_psn;
	}

	/**
	 * @return SO..C60_WEB.S_UPDT 
	 */
	public String getS_updt() {
		return s_updt;
	}

	/**
	 * @param s_updt SO..C60_WEB.S_UPDT 
	 */
	public void setS_updt(String s_updt) {
		this.s_updt = s_updt;
	}

	/**
	 * @return SO..C60_WEB.S_UPTM 
	 */
	public String getS_uptm() {
		return s_uptm;
	}

	/**
	 * @param s_uptm SO..C60_WEB.S_UPTM 
	 */
	public void setS_uptm(String s_uptm) {
		this.s_uptm = s_uptm;
	}

	/**
	 * @return SO..C60_WEB.USRID 
	 */
	public String getUsrid() {
		return usrid;
	}

	/**
	 * @param usrid SO..C60_WEB.USRID 
	 */
	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

}
