package com.sertek.table;

/**
 * SO..C61 <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:30.77<br>
 * 
 */
public class C61 extends BaseTable {

	/**
	 * SO..C61.CRTID 
	 */
	private String crtid = "";

	/**
	 * SO..C61.SYS 
	 */
	private String sys = "";

	/**
	 * SO..C61.C_NO 
	 */
	private String c_no = "";

	/**
	 * SO..C61.SYSID 
	 */
	private String sysid = "";

	/**
	 * SO..C61.IDNM 
	 */
	private String idnm = "";

	/**
	 * SO..C61.NAT 
	 */
	private String nat = "";

	/**
	 * SO..C61.P_KD 
	 */
	private String p_kd = "";

	/**
	 * SO..C61.CLNM 
	 */
	private String clnm = "";

	/**
	 * SO..C61.CLNM_E 
	 */
	private String clnm_e = "";

	/**
	 * SO..C61.IDNO 
	 */
	private String idno = "";

	/**
	 * SO..C61.SEX 
	 */
	private String sex = "";

	/**
	 * SO..C61.BIRDT 
	 */
	private String birdt = "";

	/**
	 * SO..C61.EMAIL 
	 */
	private String email = "";

	/**
	 * SO..C61.PFS 
	 */
	private String pfs = "";

	/**
	 * SO..C61.TITLE 
	 */
	private String title = "";

	/**
	 * SO..C61.TITLE_E 
	 */
	private String title_e = "";

	/**
	 * SO..C61.TEL 
	 */
	private String tel = "";

	/**
	 * SO..C61.FAX 
	 */
	private String fax = "";

	/**
	 * SO..C61.ZIP 
	 */
	private String zip = "";

	/**
	 * SO..C61.CITY 
	 */
	private String city = "";

	/**
	 * SO..C61.AREA 
	 */
	private String area = "";

	/**
	 * SO..C61.ADDR 
	 */
	private String addr = "";

	/**
	 * SO..C61.ADDR_E 
	 */
	private String addr_e = "";

	/**
	 * SO..C61.USRID 
	 */
	private String usrid = "";

	/**
	 * SO..C61.YESREAD 
	 */
	private String yesread = "";

	/**
	 * SO..C61.ISQRY 
	 */
	private String isqry = "";

	/**
	 * @return SO..C61.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..C61.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

	/**
	 * @return SO..C61.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..C61.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..C61.C_NO 
	 */
	public String getC_no() {
		return c_no;
	}

	/**
	 * @param c_no SO..C61.C_NO 
	 */
	public void setC_no(String c_no) {
		this.c_no = c_no;
	}

	/**
	 * @return SO..C61.SYSID 
	 */
	public String getSysid() {
		return sysid;
	}

	/**
	 * @param sysid SO..C61.SYSID 
	 */
	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	/**
	 * @return SO..C61.IDNM 
	 */
	public String getIdnm() {
		return idnm;
	}

	/**
	 * @param idnm SO..C61.IDNM 
	 */
	public void setIdnm(String idnm) {
		this.idnm = idnm;
	}

	/**
	 * @return SO..C61.NAT 
	 */
	public String getNat() {
		return nat;
	}

	/**
	 * @param nat SO..C61.NAT 
	 */
	public void setNat(String nat) {
		this.nat = nat;
	}

	/**
	 * @return SO..C61.P_KD 
	 */
	public String getP_kd() {
		return p_kd;
	}

	/**
	 * @param p_kd SO..C61.P_KD 
	 */
	public void setP_kd(String p_kd) {
		this.p_kd = p_kd;
	}

	/**
	 * @return SO..C61.CLNM 
	 */
	public String getClnm() {
		return clnm;
	}

	/**
	 * @param clnm SO..C61.CLNM 
	 */
	public void setClnm(String clnm) {
		this.clnm = clnm;
	}

	/**
	 * @return SO..C61.CLNM_E 
	 */
	public String getClnm_e() {
		return clnm_e;
	}

	/**
	 * @param clnm_e SO..C61.CLNM_E 
	 */
	public void setClnm_e(String clnm_e) {
		this.clnm_e = clnm_e;
	}

	/**
	 * @return SO..C61.IDNO 
	 */
	public String getIdno() {
		return idno;
	}

	/**
	 * @param idno SO..C61.IDNO 
	 */
	public void setIdno(String idno) {
		this.idno = idno;
	}

	/**
	 * @return SO..C61.SEX 
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * @param sex SO..C61.SEX 
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * @return SO..C61.BIRDT 
	 */
	public String getBirdt() {
		return decrypt(birdt);
	}

	/**
	 * @param birdt SO..C61.BIRDT 
	 */
	public void setBirdt(String birdt) {
		this.birdt = birdt;
	}

	/**
	 * @return SO..C61.EMAIL 
	 */
	public String getEmail() {
		return decrypt(email);
	}

	/**
	 * @param email SO..C61.EMAIL 
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return SO..C61.PFS 
	 */
	public String getPfs() {
		return decrypt(pfs);
	}

	/**
	 * @param pfs SO..C61.PFS 
	 */
	public void setPfs(String pfs) {
		this.pfs = pfs;
	}

	/**
	 * @return SO..C61.TITLE 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * @param title SO..C61.TITLE 
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * @return SO..C61.TITLE_E 
	 */
	public String getTitle_e() {
		return title_e;
	}

	/**
	 * @param title_e SO..C61.TITLE_E 
	 */
	public void setTitle_e(String title_e) {
		this.title_e = title_e;
	}

	/**
	 * @return SO..C61.TEL 
	 */
	public String getTel() {
		return decrypt(tel);
	}

	/**
	 * @param tel SO..C61.TEL 
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * @return SO..C61.FAX 
	 */
	public String getFax() {
		return decrypt(fax);
	}

	/**
	 * @param fax SO..C61.FAX 
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * @return SO..C61.ZIP 
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * @param zip SO..C61.ZIP 
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * @return SO..C61.CITY 
	 */
	public String getCity() {
		return city;
	}

	/**
	 * @param city SO..C61.CITY 
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * @return SO..C61.AREA 
	 */
	public String getArea() {
		return area;
	}

	/**
	 * @param area SO..C61.AREA 
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * @return SO..C61.ADDR 
	 */
	public String getAddr() {
		return decrypt(addr);
	}

	/**
	 * @param addr SO..C61.ADDR 
	 */
	public void setAddr(String addr) {
		this.addr = addr;
	}

	/**
	 * @return SO..C61.ADDR_E 
	 */
	public String getAddr_e() {
		return decrypt(addr_e);
	}

	/**
	 * @param addr_e SO..C61.ADDR_E 
	 */
	public void setAddr_e(String addr_e) {
		this.addr_e = addr_e;
	}

	/**
	 * @return SO..C61.USRID 
	 */
	public String getUsrid() {
		return usrid;
	}

	/**
	 * @param usrid SO..C61.USRID 
	 */
	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

	/**
	 * @return SO..C61.YESREAD 
	 */
	public String getYesread() {
		return yesread;
	}

	/**
	 * @param yesread SO..C61.YESREAD 
	 */
	public void setYesread(String yesread) {
		this.yesread = yesread;
	}

	/**
	 * @return SO..C61.ISQRY 
	 */
	public String getIsqry() {
		return isqry;
	}

	/**
	 * @param isqry SO..C61.ISQRY 
	 */
	public void setIsqry(String isqry) {
		this.isqry = isqry;
	}

}
