package com.sertek.table;

/**
 * SO..C6A_D <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:30.832<br>
 * 
 */
public class C6A_D extends BaseTable {

	/**
	 * SO..C6A_D.CRTID 
	 */
	private String crtid = "";

	/**
	 * SO..C6A_D.SYS 
	 */
	private String sys = "";

	/**
	 * SO..C6A_D.INSDT 
	 */
	private String insdt = "";

	/**
	 * SO..C6A_D.INSTM 
	 */
	private String instm = "";

	/**
	 * SO..C6A_D.C_NO 
	 */
	private String c_no = "";

	/**
	 * SO..C6A_D.SYSID 
	 */
	private String sysid = "";

	/**
	 * SO..C6A_D.AGSYSID 
	 */
	private String agsysid = "";

	/**
	 * SO..C6A_D.CLNM 
	 */
	private String clnm = "";

	/**
	 * SO..C6A_D.ZIP 
	 */
	private String zip = "";

	/**
	 * SO..C6A_D.CITY 
	 */
	private String city = "";

	/**
	 * SO..C6A_D.AREA 
	 */
	private String area = "";

	/**
	 * SO..C6A_D.ADDR 
	 */
	private String addr = "";

	/**
	 * @return SO..C6A_D.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..C6A_D.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

	/**
	 * @return SO..C6A_D.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..C6A_D.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..C6A_D.INSDT 
	 */
	public String getInsdt() {
		return insdt;
	}

	/**
	 * @param insdt SO..C6A_D.INSDT 
	 */
	public void setInsdt(String insdt) {
		this.insdt = insdt;
	}

	/**
	 * @return SO..C6A_D.INSTM 
	 */
	public String getInstm() {
		return instm;
	}

	/**
	 * @param instm SO..C6A_D.INSTM 
	 */
	public void setInstm(String instm) {
		this.instm = instm;
	}

	/**
	 * @return SO..C6A_D.C_NO 
	 */
	public String getC_no() {
		return c_no;
	}

	/**
	 * @param c_no SO..C6A_D.C_NO 
	 */
	public void setC_no(String c_no) {
		this.c_no = c_no;
	}

	/**
	 * @return SO..C6A_D.SYSID 
	 */
	public String getSysid() {
		return sysid;
	}

	/**
	 * @param sysid SO..C6A_D.SYSID 
	 */
	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	/**
	 * @return SO..C6A_D.AGSYSID 
	 */
	public String getAgsysid() {
		return agsysid;
	}

	/**
	 * @param agsysid SO..C6A_D.AGSYSID 
	 */
	public void setAgsysid(String agsysid) {
		this.agsysid = agsysid;
	}

	/**
	 * @return SO..C6A_D.CLNM 
	 */
	public String getClnm() {
		return clnm;
	}

	/**
	 * @param clnm SO..C6A_D.CLNM 
	 */
	public void setClnm(String clnm) {
		this.clnm = clnm;
	}

	/**
	 * @return SO..C6A_D.ZIP 
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * @param zip SO..C6A_D.ZIP 
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * @return SO..C6A_D.CITY 
	 */
	public String getCity() {
		return city;
	}

	/**
	 * @param city SO..C6A_D.CITY 
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * @return SO..C6A_D.AREA 
	 */
	public String getArea() {
		return area;
	}

	/**
	 * @param area SO..C6A_D.AREA 
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * @return SO..C6A_D.ADDR 
	 */
	public String getAddr() {
		return decrypt(addr);
	}

	/**
	 * @param addr SO..C6A_D.ADDR 
	 */
	public void setAddr(String addr) {
		this.addr = addr;
	}

}
