package com.sertek.table;

/**
 * SO..C6B <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:30.863<br>
 * 
 */
public class C6M extends BaseTable {

	private String crtid = "";
	private String sys = "";
	private String c_no = "";
	private String org_kd = "";
	private String org_id = "";
	private String org_nm = "";
	private String org_date = "";
	private String org_no = "";
	public String getCrtid() {
		return crtid;
	}
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}
	public String getSys() {
		return sys;
	}
	public void setSys(String sys) {
		this.sys = sys;
	}
	public String getC_no() {
		return c_no;
	}
	public void setC_no(String c_no) {
		this.c_no = c_no;
	}
	public String getOrg_kd() {
		return org_kd;
	}
	public void setOrg_kd(String org_kd) {
		this.org_kd = org_kd;
	}
	public String getOrg_id() {
		return org_id;
	}
	public void setOrg_id(String org_id) {
		this.org_id = org_id;
	}
	public String getOrg_nm() {
		return org_nm;
	}
	public void setOrg_nm(String org_nm) {
		this.org_nm = org_nm;
	}
	public String getOrg_date() {
		return org_date;
	}
	public void setOrg_date(String org_date) {
		this.org_date = org_date;
	}
	public String getOrg_no() {
		return org_no;
	}
	public void setOrg_no(String org_no) {
		this.org_no = org_no;
	}

}
