package com.sertek.table;

/**
 * SO..CITYAREA <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:30.941<br>
 * 
 */
public class CITYAREA extends BaseTable {

	/**
	 * SO..CITYAREA.ZIPCODE 
	 */
	private String zipcode = "";

	/**
	 * SO..CITYAREA.CITY 
	 */
	private String city = "";

	/**
	 * SO..CITYAREA.AREA 
	 */
	private String area = "";

	/**
	 * @return SO..CITYAREA.ZIPCODE 
	 */
	public String getZipcode() {
		return zipcode;
	}

	/**
	 * @param zipcode SO..CITYAREA.ZIPCODE 
	 */
	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	/**
	 * @return SO..CITYAREA.CITY 
	 */
	public String getCity() {
		return city;
	}

	/**
	 * @param city SO..CITYAREA.CITY 
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * @return SO..CITYAREA.AREA 
	 */
	public String getArea() {
		return area;
	}

	/**
	 * @param area SO..CITYAREA.AREA 
	 */
	public void setArea(String area) {
		this.area = area;
	}

}
