package com.sertek.table;

/**
 * SO..COURT <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:30.972<br>
 * 
 */
public class COURT extends BaseTable {

	/**
	 * SO..COURT.CRTID 
	 */
	private String crtid = "";

	/**
	 * SO..COURT.CRTNM 
	 */
	private String crtnm = "";

	/**
	 * SO..COURT.CRTSEQ 
	 */
	private String crtseq = "";

	/**
	 * SO..COURT.CRTKD 
	 */
	private String crtkd = "";

	/**
	 * SO..COURT.SYSKD 
	 */
	private String syskd = "";

	/**
	 * @return SO..COURT.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..COURT.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

	/**
	 * @return SO..COURT.CRTNM 
	 */
	public String getCrtnm() {
		return crtnm;
	}

	/**
	 * @param crtnm SO..COURT.CRTNM 
	 */
	public void setCrtnm(String crtnm) {
		this.crtnm = crtnm;
	}

	/**
	 * @return SO..COURT.CRTSEQ 
	 */
	public String getCrtseq() {
		return crtseq;
	}

	/**
	 * @param crtseq SO..COURT.CRTSEQ 
	 */
	public void setCrtseq(String crtseq) {
		this.crtseq = crtseq;
	}

	/**
	 * @return SO..COURT.CRTKD 
	 */
	public String getCrtkd() {
		return crtkd;
	}

	/**
	 * @param crtkd SO..COURT.CRTKD 
	 */
	public void setCrtkd(String crtkd) {
		this.crtkd = crtkd;
	}

	/**
	 * @return SO..COURT.SYSKD 
	 */
	public String getSyskd() {
		return syskd;
	}

	/**
	 * @param syskd SO..COURT.SYSKD 
	 */
	public void setSyskd(String syskd) {
		this.syskd = syskd;
	}

}
