package com.sertek.table;

/**
 * SO..ENSET <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.004<br>
 * 
 */
public class ENSET extends BaseTable {

	/**
	 * SO..ENSET.TBLNM 
	 */
	private String tblnm = "";

	/**
	 * SO..ENSET.COLNM 
	 */
	private String colnm = "";

	/**
	 * SO..ENSET.OLEN 
	 */
	private String olen = "";

	/**
	 * @return SO..ENSET.TBLNM 
	 */
	public String getTblnm() {
		return tblnm;
	}

	/**
	 * @param tblnm SO..ENSET.TBLNM 
	 */
	public void setTblnm(String tblnm) {
		this.tblnm = tblnm;
	}

	/**
	 * @return SO..ENSET.COLNM 
	 */
	public String getColnm() {
		return colnm;
	}

	/**
	 * @param colnm SO..ENSET.COLNM 
	 */
	public void setColnm(String colnm) {
		this.colnm = colnm;
	}

	/**
	 * @return SO..ENSET.OLEN 
	 */
	public String getOlen() {
		return olen;
	}

	/**
	 * @param olen SO..ENSET.OLEN 
	 */
	public void setOlen(String olen) {
		this.olen = olen;
	}

}
