package com.sertek.table;

/**
 * SO..R04_del <br>
 * generated by SqlServerIbator on 2014-06-07 14:25:27.82<br>
 * 
 */
public class R04_del extends BaseTable {

	/**
	 * SO..R04_del.HDAY 
	 */
	private String hday = "";

	/**
	 * SO..R04_del.RMK 
	 */
	private String rmk = "";

	/**
	 * @return SO..R04_del.HDAY 
	 */
	public String getHday() {
		return hday;
	}

	/**
	 * @param hday SO..R04_del.HDAY 
	 */
	public void setHday(String hday) {
		this.hday = hday;
	}

	/**
	 * @return SO..R04_del.RMK 
	 */
	public String getRmk() {
		return rmk;
	}

	/**
	 * @param rmk SO..R04_del.RMK 
	 */
	public void setRmk(String rmk) {
		this.rmk = rmk;
	}

}
