package com.sertek.table;

/**
 * SO..rcvCRMlog <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.035<br>
 * 
 */
public class rcvCRMlog extends BaseTable {

	/**
	 * SO..rcvCRMlog.XMLID 
	 */
	private String xmlid = "";

	/**
	 * SO..rcvCRMlog.CRTID 
	 */
	private String crtid = "";

	/**
	 * SO..rcvCRMlog.SYS 
	 */
	private String sys = "";

	/**
	 * SO..rcvCRMlog.INSDT 
	 */
	private String insdt = "";

	/**
	 * SO..rcvCRMlog.INSTM 
	 */
	private String instm = "";

	/**
	 * SO..rcvCRMlog.DOC_NO 
	 */
	private String doc_no = "";

	/**
	 * SO..rcvCRMlog.CRMYY 
	 */
	private String crmyy = "";

	/**
	 * SO..rcvCRMlog.CRMID 
	 */
	private String crmid = "";

	/**
	 * SO..rcvCRMlog.CRMNO 
	 */
	private String crmno = "";

	/**
	 * SO..rcvCRMlog.DPT 
	 */
	private String dpt = "";

	/**
	 * SO..rcvCRMlog.CRMDT 
	 */
	private String crmdt = "";

	/**
	 * SO..rcvCRMlog.PEDT 
	 */
	private String pedt = "";

	/**
	 * SO..rcvCRMlog.P_STATUS 
	 */
	private String p_status = "";

	/**
	 * SO..rcvCRMlog.RELIEVE 
	 */
	private String relieve = "";

	private String crt_apv = "";
	
	private String tocrtid = "";
	
	private String tosys = "";
	
	private String tostatus = "";
	
	private String tosddtm = "";
	
	private String toflag = "";
	
	private String msg = "";
	
	private String usrid = "";
	
	public String getUsrid() {
		return usrid;
	}

	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

	public String getTocrtid() {
		return tocrtid;
	}

	public void setTocrtid(String tocrtid) {
		this.tocrtid = tocrtid;
	}

	public String getTosys() {
		return tosys;
	}

	public void setTosys(String tosys) {
		this.tosys = tosys;
	}

	public String getTostatus() {
		return tostatus;
	}

	public void setTostatus(String tostatus) {
		this.tostatus = tostatus;
	}

	public String getTosddtm() {
		return tosddtm;
	}

	public void setTosddtm(String tosddtm) {
		this.tosddtm = tosddtm;
	}

	public String getToflag() {
		return toflag;
	}

	public void setToflag(String toflag) {
		this.toflag = toflag;
	}

	public String getMsg() {
		return msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	public String getCrt_apv() {
		return crt_apv;
	}

	public void setCrt_apv(String crt_apv) {
		this.crt_apv = crt_apv;
	}

	/**
	 * @return SO..rcvCRMlog.XMLID 
	 */
	public String getXmlid() {
		return xmlid;
	}

	/**
	 * @param xmlid SO..rcvCRMlog.XMLID 
	 */
	public void setXmlid(String xmlid) {
		this.xmlid = xmlid;
	}

	/**
	 * @return SO..rcvCRMlog.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..rcvCRMlog.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

	/**
	 * @return SO..rcvCRMlog.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..rcvCRMlog.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..rcvCRMlog.INSDT 
	 */
	public String getInsdt() {
		return insdt;
	}

	/**
	 * @param insdt SO..rcvCRMlog.INSDT 
	 */
	public void setInsdt(String insdt) {
		this.insdt = insdt;
	}

	/**
	 * @return SO..rcvCRMlog.INSTM 
	 */
	public String getInstm() {
		return instm;
	}

	/**
	 * @param instm SO..rcvCRMlog.INSTM 
	 */
	public void setInstm(String instm) {
		this.instm = instm;
	}

	/**
	 * @return SO..rcvCRMlog.DOC_NO 
	 */
	public String getDoc_no() {
		return doc_no;
	}

	/**
	 * @param doc_no SO..rcvCRMlog.DOC_NO 
	 */
	public void setDoc_no(String doc_no) {
		this.doc_no = doc_no;
	}

	/**
	 * @return SO..rcvCRMlog.CRMYY 
	 */
	public String getCrmyy() {
		return crmyy;
	}

	/**
	 * @param crmyy SO..rcvCRMlog.CRMYY 
	 */
	public void setCrmyy(String crmyy) {
		this.crmyy = crmyy;
	}

	/**
	 * @return SO..rcvCRMlog.CRMID 
	 */
	public String getCrmid() {
		return crmid;
	}

	/**
	 * @param crmid SO..rcvCRMlog.CRMID 
	 */
	public void setCrmid(String crmid) {
		this.crmid = crmid;
	}

	/**
	 * @return SO..rcvCRMlog.CRMNO 
	 */
	public String getCrmno() {
		return crmno;
	}

	/**
	 * @param crmno SO..rcvCRMlog.CRMNO 
	 */
	public void setCrmno(String crmno) {
		this.crmno = crmno;
	}

	/**
	 * @return SO..rcvCRMlog.DPT 
	 */
	public String getDpt() {
		return dpt;
	}

	/**
	 * @param dpt SO..rcvCRMlog.DPT 
	 */
	public void setDpt(String dpt) {
		this.dpt = dpt;
	}

	/**
	 * @return SO..rcvCRMlog.CRMDT 
	 */
	public String getCrmdt() {
		return crmdt;
	}

	/**
	 * @param crmdt SO..rcvCRMlog.CRMDT 
	 */
	public void setCrmdt(String crmdt) {
		this.crmdt = crmdt;
	}

	/**
	 * @return SO..rcvCRMlog.PEDT 
	 */
	public String getPedt() {
		return pedt;
	}

	/**
	 * @param pedt SO..rcvCRMlog.PEDT 
	 */
	public void setPedt(String pedt) {
		this.pedt = pedt;
	}

	/**
	 * @return SO..rcvCRMlog.P_STATUS 
	 */
	public String getP_status() {
		return p_status;
	}

	/**
	 * @param p_status SO..rcvCRMlog.P_STATUS 
	 */
	public void setP_status(String p_status) {
		this.p_status = p_status;
	}

	/**
	 * @return SO..rcvCRMlog.RELIEVE 
	 */
	public String getRelieve() {
		return relieve;
	}

	/**
	 * @param relieve SO..rcvCRMlog.RELIEVE 
	 */
	public void setRelieve(String relieve) {
		this.relieve = relieve;
	}

}
