package com.sertek.table;

/**
 * SO..rcvxmldata <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.066<br>
 * 
 */
public class rcvxmldata extends BaseTable {

	/**
	 * SO..rcvxmldata.XMLID 
	 */
	private String xmlid = "";

	/**
	 * SO..rcvxmldata.PRGID 
	 */
	private String prgid = "";

	/**
	 * SO..rcvxmldata.SYSDT 
	 */
	private String sysdt = "";

	/**
	 * SO..rcvxmldata.SYSTM 
	 */
	private String systm = "";

	/**
	 * SO..rcvxmldata.XMLDATA 
	 */
	private String xmldata = "";

	/**
	 * SO..rcvxmldata.OKFLAG 
	 */
	private String okflag = "";

	/**
	 * SO..rcvxmldata.INSDT 
	 */
	private String insdt = "";

	/**
	 * SO..rcvxmldata.INSTM 
	 */
	private String instm = "";

	/**
	 * @return SO..rcvxmldata.XMLID 
	 */
	public String getXmlid() {
		return xmlid;
	}

	/**
	 * @param xmlid SO..rcvxmldata.XMLID 
	 */
	public void setXmlid(String xmlid) {
		this.xmlid = xmlid;
	}

	/**
	 * @return SO..rcvxmldata.PRGID 
	 */
	public String getPrgid() {
		return prgid;
	}

	/**
	 * @param prgid SO..rcvxmldata.PRGID 
	 */
	public void setPrgid(String prgid) {
		this.prgid = prgid;
	}

	/**
	 * @return SO..rcvxmldata.SYSDT 
	 */
	public String getSysdt() {
		return sysdt;
	}

	/**
	 * @param sysdt SO..rcvxmldata.SYSDT 
	 */
	public void setSysdt(String sysdt) {
		this.sysdt = sysdt;
	}

	/**
	 * @return SO..rcvxmldata.SYSTM 
	 */
	public String getSystm() {
		return systm;
	}

	/**
	 * @param systm SO..rcvxmldata.SYSTM 
	 */
	public void setSystm(String systm) {
		this.systm = systm;
	}

	/**
	 * @return SO..rcvxmldata.XMLDATA 
	 */
	public String getXmldata() {
		return xmldata;
	}

	/**
	 * @param xmldata SO..rcvxmldata.XMLDATA 
	 */
	public void setXmldata(String xmldata) {
		this.xmldata = xmldata;
	}

	/**
	 * @return SO..rcvxmldata.OKFLAG 
	 */
	public String getOkflag() {
		return okflag;
	}

	/**
	 * @param okflag SO..rcvxmldata.OKFLAG 
	 */
	public void setOkflag(String okflag) {
		this.okflag = okflag;
	}

	/**
	 * @return SO..rcvxmldata.INSDT 
	 */
	public String getInsdt() {
		return insdt;
	}

	/**
	 * @param insdt SO..rcvxmldata.INSDT 
	 */
	public void setInsdt(String insdt) {
		this.insdt = insdt;
	}

	/**
	 * @return SO..rcvxmldata.INSTM 
	 */
	public String getInstm() {
		return instm;
	}

	/**
	 * @param instm SO..rcvxmldata.INSTM 
	 */
	public void setInstm(String instm) {
		this.instm = instm;
	}

}
