package com.sertek.table;

/**
 * SO..RESETPSWD <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.128<br>
 * 
 */
public class RESETPSWD extends BaseTable {

	/**
	 * SO..RESETPSWD.SN 
	 */
	private String sn = "";

	/**
	 * SO..RESETPSWD.USRID 
	 */
	private String usrid = "";

	/**
	 * SO..RESETPSWD.REQDT 
	 */
	private String reqdt = "";

	/**
	 * SO..RESETPSWD.REQTM 
	 */
	private String reqtm = "";

	/**
	 * @return SO..RESETPSWD.STATUS 
	 */
	public String status = ""; 

	/**
	 * @param SO..RESETPSWD.SN 
	 */
	public void setSn(String sn) {
		this.sn = sn;
	}

	/**
	 * @return SO..RESETPSWD.SN 
	 */
	public String getSn() {
		return sn;
	}

	/**
	 * @param argnm SO..RESETPSWD.USRID 
	 */
	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

	/**
	 * @return SO..RESETPSWD.USRID 
	 */
	public String getUsrid() {
		return usrid;
	}

	/**
	 * @param argvl SO..RESETPSWD.REQDT 
	 */
	public void setReqdt(String reqdt) {
		this.reqdt = reqdt;
	}

	/**
	 * @return SO..RESETPSWD.REQDT 
	 */
	public String getReqdt() {
		return reqdt;
	}

	/**
	 * @param rmk SO..RESETPSWD.REQTM 
	 */
	public void setReqtm(String reqtm) {
		this.reqtm = reqtm;
	}
	
	/**
	 * @return SO..RESETPSWD.REQTM 
	 */
	public String getReqtm() {
		return reqtm;
	}
	
	/**
	 * @param rmk SO..RESETPSWD.STATUS 
	 */
	public void setStatus(String status) {
		this.status = status;
	}
	
	/**
	 * @return SO..RESETPSWD.STATUS 
	 */
	public String getStatus() {
		return status;
	}


}
