package com.sertek.table;

/**
 * SO..S03 <br>
 * generated by SqlServerIbator on 2014-11-11 15:49:17.38<br>
 * 
 */
public class S03 extends BaseTable {

	private String owner = "";
	
	private String syskd = "";
	
	private String scd = "";
	
	private String sys = "";
	
	public String getSys() {
		return sys;
	}

	public void setSys(String sys) {
		this.sys = sys;
	}

	private String lawofficeadmincnt = "";
	
	public String getLawofficeadmincnt() {
		return lawofficeadmincnt;
	}

	public void setLawofficeadmincnt(String lawofficeadmincnt) {
		this.lawofficeadmincnt = lawofficeadmincnt;
	}

	public String getScd() {
		return scd;
	}

	public void setScd(String scd) {
		this.scd = scd;
	}

	private String scdnm = "";
	
	private String use_flag = "";
	
	private String lawoffice = "";
	
	private String wday = "";
	
	private String ok_id = "";
	
	private String group_id = "";
	
	public String getGroup_id() {
		return group_id;
	}

	public void setGroup_id(String group_id) {
		this.group_id = group_id;
	}

	public String getOk_id() {
		return ok_id;
	}

	public void setOk_id(String ok_id) {
		this.ok_id = ok_id;
	}

	public String getLawoffice() {
		return decrypt(lawoffice);
	}

	public void setLawoffice(String lawoffice) {
		this.lawoffice = lawoffice;
	}

	public String getWday() {
		return decrypt(wday);
	}

	public void setWday(String wday) {
		this.wday = wday;
	}

	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getSyskd() {
		return syskd;
	}

	public void setSyskd(String syskd) {
		this.syskd = syskd;
	}

	public String getScdnm() {
		return scdnm;
	}

	public void setScdnm(String scdnm) {
		this.scdnm = scdnm;
	}

	public String getUse_flag() {
		return use_flag;
	}

	public void setUse_flag(String use_flag) {
		this.use_flag = use_flag;
	}

	/**
	 * SO..S03.USRID 
	 */
	private String usrid = "";

	/**
	 * SO..S03.PSWD 
	 */
	private String pswd = "";

	/**
	 * SO..S03.USRNM 
	 */
	private String usrnm = "";

	/**
	 * SO..S03.IDNO 
	 */
	private String idno = "";

	/**
	 * SO..S03.EMAIL 
	 */
	private String email = "";

	/**
	 * SO..S03.TEL 
	 */
	private String tel = "";

	/**
	 * SO..S03.MOBILE 
	 */
	private String mobile = "";

	/**
	 * SO..S03.ADDR 
	 */
	private String addr = "";

	/**
	 * SO..S03.ENABDT 
	 */
	private String enabdt = "";

	/**
	 * SO..S03.DSABDT 
	 */
	private String dsabdt = "";

	/**
	 * SO..S03.STATUS 
	 */
	private String status = "";

	/**
	 * SO..S03.LSTLGNDT 
	 */
	private String lstlgndt = "";

	/**
	 * SO..S03.LSTLGNTM 
	 */
	private String lstlgntm = "";

	/**
	 * SO..S03.PSWDCNT 
	 */
	private String pswdcnt = "";

	/**
	 * SO..S03.PRIV 
	 */
	private String priv = "";

	/**
	 * SO..S03.VIP_TYPE 
	 */
	private String vip_type = "";
	
	/**
	 * SO..S03.LASTPWDTIME 
	 */
	private String lastpwdtime = "";

	/**
	 * @return SO..S03.USRID 
	 */
	public String getUsrid() {
		return usrid;
	}

	/**
	 * @param usrid SO..S03.USRID 
	 */
	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

	/**
	 * @return SO..S03.PSWD 
	 */
	public String getPswd() {
		return decrypt(pswd);
	}

	/**
	 * @param pswd SO..S03.PSWD 
	 */
	public void setPswd(String pswd) {
		this.pswd = pswd;
	}

	/**
	 * @return SO..S03.USRNM 
	 */
	public String getUsrnm() {
		return decrypt(usrnm);
	}

	/**
	 * @param usrnm SO..S03.USRNM 
	 */
	public void setUsrnm(String usrnm) {
		this.usrnm = usrnm;
	}

	/**
	 * @return SO..S03.IDNO 
	 */
	public String getIdno() {
		return decrypt(idno);
	}

	/**
	 * @param idno SO..S03.IDNO 
	 */
	public void setIdno(String idno) {
		this.idno = idno;
	}

	/**
	 * @return SO..S03.EMAIL 
	 */
	public String getEmail() {
		return decrypt(email);
	}

	/**
	 * @param email SO..S03.EMAIL 
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return SO..S03.TEL 
	 */
	public String getTel() {
		return decrypt(tel);
	}

	/**
	 * @param tel SO..S03.TEL 
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * @return SO..S03.MOBILE 
	 */
	public String getMobile() {
		return decrypt(mobile);
	}

	/**
	 * @param mobile SO..S03.MOBILE 
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * @return SO..S03.ADDR 
	 */
	public String getAddr() {
		return decrypt(addr);
	}

	/**
	 * @param addr SO..S03.ADDR 
	 */
	public void setAddr(String addr) {
		this.addr = addr;
	}

	/**
	 * @return SO..S03.ENABDT 
	 */
	public String getEnabdt() {
		return enabdt;
	}

	/**
	 * @param enabdt SO..S03.ENABDT 
	 */
	public void setEnabdt(String enabdt) {
		this.enabdt = enabdt;
	}

	/**
	 * @return SO..S03.DSABDT 
	 */
	public String getDsabdt() {
		return dsabdt;
	}

	/**
	 * @param dsabdt SO..S03.DSABDT 
	 */
	public void setDsabdt(String dsabdt) {
		this.dsabdt = dsabdt;
	}

	/**
	 * @return SO..S03.STATUS 
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status SO..S03.STATUS 
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return SO..S03.LSTLGNDT 
	 */
	public String getLstlgndt() {
		return lstlgndt;
	}

	/**
	 * @param lstlgndt SO..S03.LSTLGNDT 
	 */
	public void setLstlgndt(String lstlgndt) {
		this.lstlgndt = lstlgndt;
	}

	/**
	 * @return SO..S03.LSTLGNTM 
	 */
	public String getLstlgntm() {
		return lstlgntm;
	}

	/**
	 * @param lstlgntm SO..S03.LSTLGNTM 
	 */
	public void setLstlgntm(String lstlgntm) {
		this.lstlgntm = lstlgntm;
	}

	/**
	 * @return SO..S03.PSWDCNT 
	 */
	public String getPswdcnt() {
		return pswdcnt;
	}

	/**
	 * @param pswdcnt SO..S03.PSWDCNT 
	 */
	public void setPswdcnt(String pswdcnt) {
		this.pswdcnt = pswdcnt;
	}

	/**
	 * @return SO..S03.PRIV 
	 */
	public String getPriv() {
		return priv;
	}

	/**
	 * @param priv SO..S03.PRIV 
	 */
	public void setPriv(String priv) {
		this.priv = priv;
	}

	/**
	 * @return SO..S03.VIP_TYPE 
	 */
	public String getVip_type() {
		return vip_type;
	}

	/**
	 * @param vip_type SO..S03.VIP_TYPE 
	 */
	public void setVip_type(String vip_type) {
		this.vip_type = vip_type;
	}
	
	/**
	 * @param pswd SO..S03.LASTPWDTIME 
	 */
	public void setLastpwdtime(String lastpwdtime) {
		this.lastpwdtime = lastpwdtime;
	}

	/**
	 * @return SO..S03.LASTPWDTIME 
	 */
	public String getLastpwdtime() {
		return decrypt(lastpwdtime);
	}
}
