package com.sertek.table;

/**
 * SO..S03_ACC <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.097<br>
 * 
 */
public class S03_ACC extends BaseTable {

	/**
	 * SO..S03_ACC.USRID 
	 */
	private String usrid = "";

	/**
	 * SO..S03_ACC.IDNO 
	 */
	private String idno = "";

	/**
	 * SO..S03_ACC.BANKID 
	 */
	private String bankid = "";

	/**
	 * SO..S03_ACC.BANKACC 
	 */
	private String bankacc = "";

	/**
	 * SO..S03_ACC.ACCTYPE 
	 */
	private String acctype = "";

	/**
	 * @return SO..S03_ACC.USRID 
	 */
	public String getUsrid() {
		return usrid;
	}

	/**
	 * @param usrid SO..S03_ACC.USRID 
	 */
	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

	/**
	 * @return SO..S03_ACC.IDNO 
	 */
	public String getIdno() {
		return decrypt(idno);
	}

	/**
	 * @param idno SO..S03_ACC.IDNO 
	 */
	public void setIdno(String idno) {
		this.idno = idno;
	}

	/**
	 * @return SO..S03_ACC.BANKID 
	 */
	public String getBankid() {
		return decrypt(bankid);
	}

	/**
	 * @param bankid SO..S03_ACC.BANKID 
	 */
	public void setBankid(String bankid) {
		this.bankid = bankid;
	}

	/**
	 * @return SO..S03_ACC.BANKACC 
	 */
	public String getBankacc() {
		return decrypt(bankacc);
	}

	/**
	 * @param bankacc SO..S03_ACC.BANKACC 
	 */
	public void setBankacc(String bankacc) {
		this.bankacc = bankacc;
	}

	/**
	 * @return SO..S03_ACC.ACCTYPE 
	 */
	public String getAcctype() {
		return acctype;
	}

	/**
	 * @param acctype SO..S03_ACC.ACCTYPE 
	 */
	public void setAcctype(String acctype) {
		this.acctype = acctype;
	}

}
