package com.sertek.table;

/**
 * SO..S08 <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.128<br>
 * 
 */
public class S08 extends BaseTable {

	/**
	 * SO..S08.PRGID 
	 */
	private String prgid = "";

	/**
	 * SO..S08.ARGNM 
	 */
	private String argnm = "";

	/**
	 * SO..S08.ARGVL 
	 */
	private String argvl = "";

	/**
	 * SO..S08.RMK 
	 */
	private String rmk = "";

	/**
	 * @return SO..S08.PRGID 
	 */
	public String getPrgid() {
		return prgid;
	}

	/**
	 * @param prgid SO..S08.PRGID 
	 */
	public void setPrgid(String prgid) {
		this.prgid = prgid;
	}

	/**
	 * @return SO..S08.ARGNM 
	 */
	public String getArgnm() {
		return argnm;
	}

	/**
	 * @param argnm SO..S08.ARGNM 
	 */
	public void setArgnm(String argnm) {
		this.argnm = argnm;
	}

	/**
	 * @return SO..S08.ARGVL 
	 */
	public String getArgvl() {
		return argvl;
	}

	/**
	 * @param argvl SO..S08.ARGVL 
	 */
	public void setArgvl(String argvl) {
		this.argvl = argvl;
	}

	/**
	 * @return SO..S08.RMK 
	 */
	public String getRmk() {
		return rmk;
	}

	/**
	 * @param rmk SO..S08.RMK 
	 */
	public void setRmk(String rmk) {
		this.rmk = rmk;
	}

}
