package com.sertek.table;

/**
 * SO..S14 <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.16<br>
 * 
 */
public class S14 extends BaseTable {

	/**
	 * SO..S14.CRTID 
	 */
	private String crtid = "";

	/**
	 * SO..S14.PRGID 
	 */
	private String prgid = "";

	/**
	 * SO..S14.ARGNM 
	 */
	private String argnm = "";

	/**
	 * SO..S14.ARGVL 
	 */
	private String argvl = "";

	/**
	 * SO..S14.RMK 
	 */
	private String rmk = "";

	/**
	 * SO..S14.CRTIP 
	 */
	private String crtip = "";

	/**
	 * SO..S14.CRTIP1 
	 */
	private String crtip1 = "";

	/**
	 * @return SO..S14.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..S14.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

	/**
	 * @return SO..S14.PRGID 
	 */
	public String getPrgid() {
		return prgid;
	}

	/**
	 * @param prgid SO..S14.PRGID 
	 */
	public void setPrgid(String prgid) {
		this.prgid = prgid;
	}

	/**
	 * @return SO..S14.ARGNM 
	 */
	public String getArgnm() {
		return argnm;
	}

	/**
	 * @param argnm SO..S14.ARGNM 
	 */
	public void setArgnm(String argnm) {
		this.argnm = argnm;
	}

	/**
	 * @return SO..S14.ARGVL 
	 */
	public String getArgvl() {
		return argvl;
	}

	/**
	 * @param argvl SO..S14.ARGVL 
	 */
	public void setArgvl(String argvl) {
		this.argvl = argvl;
	}

	/**
	 * @return SO..S14.RMK 
	 */
	public String getRmk() {
		return rmk;
	}

	/**
	 * @param rmk SO..S14.RMK 
	 */
	public void setRmk(String rmk) {
		this.rmk = rmk;
	}

	/**
	 * @return SO..S14.CRTIP 
	 */
	public String getCrtip() {
		return crtip;
	}

	/**
	 * @param crtip SO..S14.CRTIP 
	 */
	public void setCrtip(String crtip) {
		this.crtip = crtip;
	}

	/**
	 * @return SO..S14.CRTIP1 
	 */
	public String getCrtip1() {
		return crtip1;
	}

	/**
	 * @param crtip1 SO..S14.CRTIP1 
	 */
	public void setCrtip1(String crtip1) {
		this.crtip1 = crtip1;
	}

}
