package com.sertek.table;

/**
 * BOS..S61 <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:38.395<br>
 * 
 */
public class S61 extends BaseTable {

	/**
	 * BOS..S61.SYS 
	 */
	private String sys = "";

	/**
	 * BOS..S61.SYSKD 
	 */
	private String syskd = "";

	/**
	 * BOS..S61.SCD 
	 */
	private String scd = "";

	/**
	 * BOS..S61.CRTID 
	 */
	private String crtid = "";

	/**
	 * BOS..S61.NAT 
	 */
	private String nat = "";

	/**
	 * BOS..S61.P_KD 
	 */
	private String p_kd = "";

	/**
	 * BOS..S61.CLNM 
	 */
	private String clnm = "";

	/**
	 * BOS..S61.CLNM_E 
	 */
	private String clnm_e = "";

	/**
	 * BOS..S61.IDNO 
	 */
	private String idno = "";

	/**
	 * BOS..S61.SEX 
	 */
	private String sex = "";

	/**
	 * BOS..S61.BIRDT 
	 */
	private String birdt = "";

	/**
	 * BOS..S61.EMAIL 
	 */
	private String email = "";

	/**
	 * BOS..S61.PFS 
	 */
	private String pfs = "";

	/**
	 * BOS..S61.TEL 
	 */
	private String tel = "";

	/**
	 * BOS..S61.FAX 
	 */
	private String fax = "";

	/**
	 * BOS..S61.ZIP 
	 */
	private String zip = "";

	/**
	 * BOS..S61.CITY 
	 */
	private String city = "";

	/**
	 * BOS..S61.AREA 
	 */
	private String area = "";

	/**
	 * BOS..S61.ADDR 
	 */
	private String addr = "";

	/**
	 * BOS..S61.ADDR_E 
	 */
	private String addr_e = "";

	/**
	 * BOS..S61.DOMAIN_NAME 
	 */
	private String domain_name = "";

	/**
	 * @return BOS..S61.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys BOS..S61.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return BOS..S61.SYSKD 
	 */
	public String getSyskd() {
		return syskd;
	}

	/**
	 * @param syskd BOS..S61.SYSKD 
	 */
	public void setSyskd(String syskd) {
		this.syskd = syskd;
	}

	/**
	 * @return BOS..S61.SCD 
	 */
	public String getScd() {
		return scd;
	}

	/**
	 * @param scd BOS..S61.SCD 
	 */
	public void setScd(String scd) {
		this.scd = scd;
	}

	/**
	 * @return BOS..S61.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid BOS..S61.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

	/**
	 * @return BOS..S61.NAT 
	 */
	public String getNat() {
		return nat;
	}

	/**
	 * @param nat BOS..S61.NAT 
	 */
	public void setNat(String nat) {
		this.nat = nat;
	}

	/**
	 * @return BOS..S61.P_KD 
	 */
	public String getP_kd() {
		return p_kd;
	}

	/**
	 * @param p_kd BOS..S61.P_KD 
	 */
	public void setP_kd(String p_kd) {
		this.p_kd = p_kd;
	}

	/**
	 * @return BOS..S61.CLNM 
	 */
	public String getClnm() {
		return clnm;
	}

	/**
	 * @param clnm BOS..S61.CLNM 
	 */
	public void setClnm(String clnm) {
		this.clnm = clnm;
	}

	/**
	 * @return BOS..S61.CLNM_E 
	 */
	public String getClnm_e() {
		return clnm_e;
	}

	/**
	 * @param clnm_e BOS..S61.CLNM_E 
	 */
	public void setClnm_e(String clnm_e) {
		this.clnm_e = clnm_e;
	}

	/**
	 * @return BOS..S61.IDNO 
	 */
	public String getIdno() {
		return idno;
	}

	/**
	 * @param idno BOS..S61.IDNO 
	 */
	public void setIdno(String idno) {
		this.idno = idno;
	}

	/**
	 * @return BOS..S61.SEX 
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * @param sex BOS..S61.SEX 
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * @return BOS..S61.BIRDT 
	 */
	public String getBirdt() {
		return birdt;
	}

	/**
	 * @param birdt BOS..S61.BIRDT 
	 */
	public void setBirdt(String birdt) {
		this.birdt = birdt;
	}

	/**
	 * @return BOS..S61.EMAIL 
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @param email BOS..S61.EMAIL 
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return BOS..S61.PFS 
	 */
	public String getPfs() {
		return pfs;
	}

	/**
	 * @param pfs BOS..S61.PFS 
	 */
	public void setPfs(String pfs) {
		this.pfs = pfs;
	}

	/**
	 * @return BOS..S61.TEL 
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * @param tel BOS..S61.TEL 
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * @return BOS..S61.FAX 
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * @param fax BOS..S61.FAX 
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * @return BOS..S61.ZIP 
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * @param zip BOS..S61.ZIP 
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * @return BOS..S61.CITY 
	 */
	public String getCity() {
		return city;
	}

	/**
	 * @param city BOS..S61.CITY 
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * @return BOS..S61.AREA 
	 */
	public String getArea() {
		return area;
	}

	/**
	 * @param area BOS..S61.AREA 
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * @return BOS..S61.ADDR 
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * @param addr BOS..S61.ADDR 
	 */
	public void setAddr(String addr) {
		this.addr = addr;
	}

	/**
	 * @return BOS..S61.ADDR_E 
	 */
	public String getAddr_e() {
		return addr_e;
	}

	/**
	 * @param addr_e BOS..S61.ADDR_E 
	 */
	public void setAddr_e(String addr_e) {
		this.addr_e = addr_e;
	}

	/**
	 * @return BOS..S61.DOMAIN_NAME 
	 */
	public String getDomain_name() {
		return domain_name;
	}

	/**
	 * @param domain_name BOS..S61.DOMAIN_NAME 
	 */
	public void setDomain_name(String domain_name) {
		this.domain_name = domain_name;
	}

}
