package com.sertek.table;

/**
 * BOS..S6A <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:38.426<br>
 * 
 */
public class S6A extends BaseTable {

	/**
	 * BOS..S6A.SYS 
	 */
	private String sys = "";

	/**
	 * BOS..S6A.SYSKD 
	 */
	private String syskd = "";

	/**
	 * BOS..S6A.SCD 
	 */
	private String scd = "";

	/**
	 * BOS..S6A.AGSCD 
	 */
	private String agscd = "";

	/**
	 * BOS..S6A.CLNM 
	 */
	private String clnm = "";

	/**
	 * BOS..S6A.ZIP 
	 */
	private String zip = "";

	/**
	 * BOS..S6A.CITY 
	 */
	private String city = "";

	/**
	 * BOS..S6A.AREA 
	 */
	private String area = "";

	/**
	 * BOS..S6A.ADDR 
	 */
	private String addr = "";

	/**
	 * @return BOS..S6A.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys BOS..S6A.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return BOS..S6A.SYSKD 
	 */
	public String getSyskd() {
		return syskd;
	}

	/**
	 * @param syskd BOS..S6A.SYSKD 
	 */
	public void setSyskd(String syskd) {
		this.syskd = syskd;
	}

	/**
	 * @return BOS..S6A.SCD 
	 */
	public String getScd() {
		return scd;
	}

	/**
	 * @param scd BOS..S6A.SCD 
	 */
	public void setScd(String scd) {
		this.scd = scd;
	}

	/**
	 * @return BOS..S6A.AGSCD 
	 */
	public String getAgscd() {
		return agscd;
	}

	/**
	 * @param agscd BOS..S6A.AGSCD 
	 */
	public void setAgscd(String agscd) {
		this.agscd = agscd;
	}

	/**
	 * @return BOS..S6A.CLNM 
	 */
	public String getClnm() {
		return clnm;
	}

	/**
	 * @param clnm BOS..S6A.CLNM 
	 */
	public void setClnm(String clnm) {
		this.clnm = clnm;
	}

	/**
	 * @return BOS..S6A.ZIP 
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * @param zip BOS..S6A.ZIP 
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * @return BOS..S6A.CITY 
	 */
	public String getCity() {
		return city;
	}

	/**
	 * @param city BOS..S6A.CITY 
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * @return BOS..S6A.AREA 
	 */
	public String getArea() {
		return area;
	}

	/**
	 * @param area BOS..S6A.AREA 
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * @return BOS..S6A.ADDR 
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * @param addr BOS..S6A.ADDR 
	 */
	public void setAddr(String addr) {
		this.addr = addr;
	}

}
