package com.sertek.table;

/**
 * BOS..S6B <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:38.473<br>
 * 
 */
public class S6B extends BaseTable {

	/**
	 * BOS..S6B.SYS 
	 */
	private String sys = "";

	/**
	 * BOS..S6B.SYSKD 
	 */
	private String syskd = "";

	/**
	 * BOS..S6B.SCD 
	 */
	private String scd = "";

	/**
	 * BOS..S6B.AGSCD 
	 */
	private String agscd = "";

	/**
	 * BOS..S6B.IDNM 
	 */
	private String idnm = "";

	/**
	 * BOS..S6B.NAT 
	 */
	private String nat = "";

	/**
	 * BOS..S6B.P_KD 
	 */
	private String p_kd = "";

	/**
	 * BOS..S6B.CLNM 
	 */
	private String clnm = "";

	/**
	 * BOS..S6B.CLNM_E 
	 */
	private String clnm_e = "";

	/**
	 * BOS..S6B.IDNO 
	 */
	private String idno = "";

	/**
	 * BOS..S6B.SEX 
	 */
	private String sex = "";

	/**
	 * BOS..S6B.BIRDT 
	 */
	private String birdt = "";

	/**
	 * BOS..S6B.EMAIL 
	 */
	private String email = "";

	/**
	 * BOS..S6B.PFS 
	 */
	private String pfs = "";

	/**
	 * BOS..S6B.TEL 
	 */
	private String tel = "";

	/**
	 * BOS..S6B.FAX 
	 */
	private String fax = "";

	/**
	 * BOS..S6B.ZIP 
	 */
	private String zip = "";

	/**
	 * BOS..S6B.CITY 
	 */
	private String city = "";

	/**
	 * BOS..S6B.AREA 
	 */
	private String area = "";

	/**
	 * BOS..S6B.ADDR 
	 */
	private String addr = "";

	/**
	 * BOS..S6B.ADDR_E 
	 */
	private String addr_e = "";

	private String title = "";
	private String title_e = "";
	
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitle_e() {
		return title_e;
	}

	public void setTitle_e(String title_e) {
		this.title_e = title_e;
	}

	/**
	 * @return BOS..S6B.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys BOS..S6B.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return BOS..S6B.SYSKD 
	 */
	public String getSyskd() {
		return syskd;
	}

	/**
	 * @param syskd BOS..S6B.SYSKD 
	 */
	public void setSyskd(String syskd) {
		this.syskd = syskd;
	}

	/**
	 * @return BOS..S6B.SCD 
	 */
	public String getScd() {
		return scd;
	}

	/**
	 * @param scd BOS..S6B.SCD 
	 */
	public void setScd(String scd) {
		this.scd = scd;
	}

	/**
	 * @return BOS..S6B.AGSCD 
	 */
	public String getAgscd() {
		return agscd;
	}

	/**
	 * @param agscd BOS..S6B.AGSCD 
	 */
	public void setAgscd(String agscd) {
		this.agscd = agscd;
	}

	/**
	 * @return BOS..S6B.IDNM 
	 */
	public String getIdnm() {
		return idnm;
	}

	/**
	 * @param idnm BOS..S6B.IDNM 
	 */
	public void setIdnm(String idnm) {
		this.idnm = idnm;
	}

	/**
	 * @return BOS..S6B.NAT 
	 */
	public String getNat() {
		return nat;
	}

	/**
	 * @param nat BOS..S6B.NAT 
	 */
	public void setNat(String nat) {
		this.nat = nat;
	}

	/**
	 * @return BOS..S6B.P_KD 
	 */
	public String getP_kd() {
		return p_kd;
	}

	/**
	 * @param p_kd BOS..S6B.P_KD 
	 */
	public void setP_kd(String p_kd) {
		this.p_kd = p_kd;
	}

	/**
	 * @return BOS..S6B.CLNM 
	 */
	public String getClnm() {
		return clnm;
	}

	/**
	 * @param clnm BOS..S6B.CLNM 
	 */
	public void setClnm(String clnm) {
		this.clnm = clnm;
	}

	/**
	 * @return BOS..S6B.CLNM_E 
	 */
	public String getClnm_e() {
		return clnm_e;
	}

	/**
	 * @param clnm_e BOS..S6B.CLNM_E 
	 */
	public void setClnm_e(String clnm_e) {
		this.clnm_e = clnm_e;
	}

	/**
	 * @return BOS..S6B.IDNO 
	 */
	public String getIdno() {
		return idno;
	}

	/**
	 * @param idno BOS..S6B.IDNO 
	 */
	public void setIdno(String idno) {
		this.idno = idno;
	}

	/**
	 * @return BOS..S6B.SEX 
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * @param sex BOS..S6B.SEX 
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * @return BOS..S6B.BIRDT 
	 */
	public String getBirdt() {
		return birdt;
	}

	/**
	 * @param birdt BOS..S6B.BIRDT 
	 */
	public void setBirdt(String birdt) {
		this.birdt = birdt;
	}

	/**
	 * @return BOS..S6B.EMAIL 
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @param email BOS..S6B.EMAIL 
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return BOS..S6B.PFS 
	 */
	public String getPfs() {
		return pfs;
	}

	/**
	 * @param pfs BOS..S6B.PFS 
	 */
	public void setPfs(String pfs) {
		this.pfs = pfs;
	}

	/**
	 * @return BOS..S6B.TEL 
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * @param tel BOS..S6B.TEL 
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * @return BOS..S6B.FAX 
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * @param fax BOS..S6B.FAX 
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * @return BOS..S6B.ZIP 
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * @param zip BOS..S6B.ZIP 
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * @return BOS..S6B.CITY 
	 */
	public String getCity() {
		return city;
	}

	/**
	 * @param city BOS..S6B.CITY 
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * @return BOS..S6B.AREA 
	 */
	public String getArea() {
		return area;
	}

	/**
	 * @param area BOS..S6B.AREA 
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * @return BOS..S6B.ADDR 
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * @param addr BOS..S6B.ADDR 
	 */
	public void setAddr(String addr) {
		this.addr = addr;
	}

	/**
	 * @return BOS..S6B.ADDR_E 
	 */
	public String getAddr_e() {
		return addr_e;
	}

	/**
	 * @param addr_e BOS..S6B.ADDR_E 
	 */
	public void setAddr_e(String addr_e) {
		this.addr_e = addr_e;
	}

}
