package com.sertek.table;

/**
 * SO..sndSO2Clog <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.284<br>
 * 
 */
public class sndSO2Clog extends BaseTable {

	/**
	 * SO..sndSO2Clog.CRTID 
	 */
	private String crtid = "";

	/**
	 * SO..sndSO2Clog.SYS 
	 */
	private String sys = "";

	/**
	 * SO..sndSO2Clog.S_KD 
	 */
	private String s_kd = "";

	/**
	 * SO..sndSO2Clog.DOC_NO 
	 */
	private String doc_no = "";

	/**
	 * SO..sndSO2Clog.S_UPDT 
	 */
	private String s_updt = "";

	/**
	 * SO..sndSO2Clog.S_UPTM 
	 */
	private String s_uptm = "";

	/**
	 * SO..sndSO2Clog.COMDT 
	 */
	private String comdt = "";

	/**
	 * SO..sndSO2Clog.COMTM 
	 */
	private String comtm = "";

	/**
	 * SO..sndSO2Clog.SENDKD 
	 */
	private String sendkd = "";

	/**
	 * @return SO..sndSO2Clog.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..sndSO2Clog.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

	/**
	 * @return SO..sndSO2Clog.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..sndSO2Clog.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..sndSO2Clog.S_KD 
	 */
	public String getS_kd() {
		return s_kd;
	}

	/**
	 * @param s_kd SO..sndSO2Clog.S_KD 
	 */
	public void setS_kd(String s_kd) {
		this.s_kd = s_kd;
	}

	/**
	 * @return SO..sndSO2Clog.DOC_NO 
	 */
	public String getDoc_no() {
		return doc_no;
	}

	/**
	 * @param doc_no SO..sndSO2Clog.DOC_NO 
	 */
	public void setDoc_no(String doc_no) {
		this.doc_no = doc_no;
	}

	/**
	 * @return SO..sndSO2Clog.S_UPDT 
	 */
	public String getS_updt() {
		return s_updt;
	}

	/**
	 * @param s_updt SO..sndSO2Clog.S_UPDT 
	 */
	public void setS_updt(String s_updt) {
		this.s_updt = s_updt;
	}

	/**
	 * @return SO..sndSO2Clog.S_UPTM 
	 */
	public String getS_uptm() {
		return s_uptm;
	}

	/**
	 * @param s_uptm SO..sndSO2Clog.S_UPTM 
	 */
	public void setS_uptm(String s_uptm) {
		this.s_uptm = s_uptm;
	}

	/**
	 * @return SO..sndSO2Clog.COMDT 
	 */
	public String getComdt() {
		return comdt;
	}

	/**
	 * @param comdt SO..sndSO2Clog.COMDT 
	 */
	public void setComdt(String comdt) {
		this.comdt = comdt;
	}

	/**
	 * @return SO..sndSO2Clog.COMTM 
	 */
	public String getComtm() {
		return comtm;
	}

	/**
	 * @param comtm SO..sndSO2Clog.COMTM 
	 */
	public void setComtm(String comtm) {
		this.comtm = comtm;
	}

	/**
	 * @return SO..sndSO2Clog.SENDKD 
	 */
	public String getSendkd() {
		return sendkd;
	}

	/**
	 * @param sendkd SO..sndSO2Clog.SENDKD 
	 */
	public void setSendkd(String sendkd) {
		this.sendkd = sendkd;
	}

}
