package com.sertek.table;

/**
 * SO..SUITKD <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.331<br>
 * 
 */
public class SUITKD extends BaseTable {

	/**
	 * SO..SUITKD.SYSKD 
	 */
	private String syskd = "";

	/**
	 * SO..SUITKD.S_KD 
	 */
	private String s_kd = "";

	/**
	 * SO..SUITKD.SUIT_ID 
	 */
	private String suit_id = "";

	/**
	 * SO..SUITKD.SUIT_NM 
	 */
	private String suit_nm = "";

	/**
	 * SO..SUITKD.SUIT_LAW 
	 */
	private String suit_law = "";

	/**
	 * SO..SUITKD.S_EXP 
	 */
	private String s_exp = "";

	/**
	 * SO..SUITKD.S_URL 
	 */
	private String s_url = "";

	/**
	 * @return SO..SUITKD.SYSKD 
	 */
	public String getSyskd() {
		return syskd;
	}

	/**
	 * @param syskd SO..SUITKD.SYSKD 
	 */
	public void setSyskd(String syskd) {
		this.syskd = syskd;
	}

	/**
	 * @return SO..SUITKD.S_KD 
	 */
	public String getS_kd() {
		return s_kd;
	}

	/**
	 * @param s_kd SO..SUITKD.S_KD 
	 */
	public void setS_kd(String s_kd) {
		this.s_kd = s_kd;
	}

	/**
	 * @return SO..SUITKD.SUIT_ID 
	 */
	public String getSuit_id() {
		return suit_id;
	}

	/**
	 * @param suit_id SO..SUITKD.SUIT_ID 
	 */
	public void setSuit_id(String suit_id) {
		this.suit_id = suit_id;
	}

	/**
	 * @return SO..SUITKD.SUIT_NM 
	 */
	public String getSuit_nm() {
		return suit_nm;
	}

	/**
	 * @param suit_nm SO..SUITKD.SUIT_NM 
	 */
	public void setSuit_nm(String suit_nm) {
		this.suit_nm = suit_nm;
	}

	/**
	 * @return SO..SUITKD.SUIT_LAW 
	 */
	public String getSuit_law() {
		return suit_law;
	}

	/**
	 * @param suit_law SO..SUITKD.SUIT_LAW 
	 */
	public void setSuit_law(String suit_law) {
		this.suit_law = suit_law;
	}

	/**
	 * @return SO..SUITKD.S_EXP 
	 */
	public String getS_exp() {
		return s_exp;
	}

	/**
	 * @param s_exp SO..SUITKD.S_EXP 
	 */
	public void setS_exp(String s_exp) {
		this.s_exp = s_exp;
	}

	/**
	 * @return SO..SUITKD.S_URL 
	 */
	public String getS_url() {
		return s_url;
	}

	/**
	 * @param s_url SO..SUITKD.S_URL 
	 */
	public void setS_url(String s_url) {
		this.s_url = s_url;
	}

}
