package com.sertek.table;

/**
 * SO..USRLOG <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.362<br>
 * 
 */
public class USRLOG extends BaseTable {

	/**
	 * SO..USRLOG.USRID 
	 */
	private String usrid = "";

	/**
	 * SO..USRLOG.USRNM 
	 */
	private String usrnm = "";

	/**
	 * SO..USRLOG.USRIP 
	 */
	private String usrip = "";

	/**
	 * SO..USRLOG.LDT 
	 */
	private String ldt = "";

	/**
	 * SO..USRLOG.LTM 
	 */
	private String ltm = "";

	/**
	 * SO..USRLOG.ACT 
	 */
	private String act = "";

	/**
	 * SO..USRLOG.DETAIL 
	 */
	private String detail = "";

	/**
	 * SO..USRLOG.C_NO 
	 */
	private String c_no = "";

	/**
	 * SO..USRLOG.MAILCON 
	 */
	private String mailcon = "";

	/**
	 * @return SO..USRLOG.USRID 
	 */
	public String getUsrid() {
		return usrid;
	}

	/**
	 * @param usrid SO..USRLOG.USRID 
	 */
	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

	/**
	 * @return SO..USRLOG.USRNM 
	 */
	public String getUsrnm() {
		return usrnm;
	}

	/**
	 * @param usrnm SO..USRLOG.USRNM 
	 */
	public void setUsrnm(String usrnm) {
		this.usrnm = usrnm;
	}

	/**
	 * @return SO..USRLOG.USRIP 
	 */
	public String getUsrip() {
		return usrip;
	}

	/**
	 * @param usrip SO..USRLOG.USRIP 
	 */
	public void setUsrip(String usrip) {
		this.usrip = usrip;
	}

	/**
	 * @return SO..USRLOG.LDT 
	 */
	public String getLdt() {
		return ldt;
	}

	/**
	 * @param ldt SO..USRLOG.LDT 
	 */
	public void setLdt(String ldt) {
		this.ldt = ldt;
	}

	/**
	 * @return SO..USRLOG.LTM 
	 */
	public String getLtm() {
		return ltm;
	}

	/**
	 * @param ltm SO..USRLOG.LTM 
	 */
	public void setLtm(String ltm) {
		this.ltm = ltm;
	}

	/**
	 * @return SO..USRLOG.ACT 
	 */
	public String getAct() {
		return decrypt(act);
	}

	/**
	 * @param act SO..USRLOG.ACT 
	 */
	public void setAct(String act) {
		this.act = act;
	}

	/**
	 * @return SO..USRLOG.DETAIL 
	 */
	public String getDetail() {
		return detail;
	}

	/**
	 * @param detail SO..USRLOG.DETAIL 
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * @return SO..USRLOG.C_NO 
	 */
	public String getC_no() {
		return c_no;
	}

	/**
	 * @param c_no SO..USRLOG.C_NO 
	 */
	public void setC_no(String c_no) {
		this.c_no = c_no;
	}

	/**
	 * @return SO..USRLOG.MAILCON 
	 */
	public String getMailcon() {
		return mailcon;
	}

	/**
	 * @param mailcon SO..USRLOG.MAILCON 
	 */
	public void setMailcon(String mailcon) {
		this.mailcon = mailcon;
	}

}
