package com.sertek.table;

/**
 * SO..xd_c01 <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.394<br>
 * 
 */
public class xd_c01 extends BaseTable {

	/**
	 * SO..xd_c01.ftpxmlnm 
	 */
	private String ftpxmlnm = "";

	/**
	 * SO..xd_c01.caseType 
	 */
	private String casetype = "";

	/**
	 * SO..xd_c01.case_type 
	 */
	private String case_type = "";

	/**
	 * SO..xd_c01.cmpdt 
	 */
	private String cmpdt = "";

	/**
	 * SO..xd_c01.costdt 
	 */
	private String costdt = "";

	/**
	 * SO..xd_c01.costis 
	 */
	private String costis = "";

	/**
	 * SO..xd_c01.costtm 
	 */
	private String costtm = "";

	/**
	 * SO..xd_c01.crmid 
	 */
	private String crmid = "";

	/**
	 * SO..xd_c01.crmis 
	 */
	private String crmis = "";

	/**
	 * SO..xd_c01.crmno 
	 */
	private String crmno = "";

	/**
	 * SO..xd_c01.crmyy 
	 */
	private String crmyy = "";

	/**
	 * SO..xd_c01.dpt 
	 */
	private String dpt = "";

	/**
	 * SO..xd_c01.dptcd 
	 */
	private String dptcd = "";

	/**
	 * SO..xd_c01.dptdt 
	 */
	private String dptdt = "";

	/**
	 * SO..xd_c01.dptis 
	 */
	private String dptis = "";

	/**
	 * SO..xd_c01.epid 
	 */
	private String epid = "";

	/**
	 * SO..xd_c01.epno 
	 */
	private String epno = "";

	/**
	 * SO..xd_c01.epyy 
	 */
	private String epyy = "";

	/**
	 * SO..xd_c01.orcrt 
	 */
	private String orcrt = "";

	/**
	 * SO..xd_c01.orcrtid 
	 */
	private String orcrtid = "";

	/**
	 * SO..xd_c01.rcvdt 
	 */
	private String rcvdt = "";

	/**
	 * SO..xd_c01.rcvid 
	 */
	private String rcvid = "";

	/**
	 * SO..xd_c01.rcvis 
	 */
	private String rcvis = "";

	/**
	 * SO..xd_c01.rcvno 
	 */
	private String rcvno = "";

	/**
	 * SO..xd_c01.rcvtm 
	 */
	private String rcvtm = "";

	/**
	 * SO..xd_c01.rcvyy 
	 */
	private String rcvyy = "";

	/**
	 * SO..xd_c01.rsn 
	 */
	private String rsn = "";

	/**
	 * SO..xd_c01.spcArea 
	 */
	private String spcarea = "";

	/**
	 * SO..xd_c01.spcCity 
	 */
	private String spccity = "";

	/**
	 * SO..xd_c01.spcOrcrt 
	 */
	private String spcorcrt = "";

	/**
	 * SO..xd_c01.spcOrcrtid 
	 */
	private String spcorcrtid = "";

	/**
	 * SO..xd_c01.spc_area 
	 */
	private String spc_area = "";

	/**
	 * SO..xd_c01.spc_city 
	 */
	private String spc_city = "";

	/**
	 * SO..xd_c01.spc_orcrt 
	 */
	private String spc_orcrt = "";

	/**
	 * SO..xd_c01.spc_orcrtid 
	 */
	private String spc_orcrtid = "";

	/**
	 * SO..xd_c01.spcis 
	 */
	private String spcis = "";

	/**
	 * SO..xd_c01.sys 
	 */
	private String sys = "";

	/**
	 * SO..xd_c01.uiddt 
	 */
	private String uiddt = "";

	/**
	 * SO..xd_c01.uidtm 
	 */
	private String uidtm = "";

	/**
	 * SO..xd_c01.updt 
	 */
	private String updt = "";

	/**
	 * SO..xd_c01.upis 
	 */
	private String upis = "";

	/**
	 * SO..xd_c01.uptm 
	 */
	private String uptm = "";

	/**
	 * SO..xd_c01.usrid 
	 */
	private String usrid = "";

	/**
	 * @return SO..xd_c01.ftpxmlnm 
	 */
	public String getFtpxmlnm() {
		return ftpxmlnm;
	}

	/**
	 * @param ftpxmlnm SO..xd_c01.ftpxmlnm 
	 */
	public void setFtpxmlnm(String ftpxmlnm) {
		this.ftpxmlnm = ftpxmlnm;
	}

	/**
	 * @return SO..xd_c01.caseType 
	 */
	public String getCasetype() {
		return casetype;
	}

	/**
	 * @param casetype SO..xd_c01.caseType 
	 */
	public void setCasetype(String casetype) {
		this.casetype = casetype;
	}

	/**
	 * @return SO..xd_c01.case_type 
	 */
	public String getCase_type() {
		return case_type;
	}

	/**
	 * @param case_type SO..xd_c01.case_type 
	 */
	public void setCase_type(String case_type) {
		this.case_type = case_type;
	}

	/**
	 * @return SO..xd_c01.cmpdt 
	 */
	public String getCmpdt() {
		return cmpdt;
	}

	/**
	 * @param cmpdt SO..xd_c01.cmpdt 
	 */
	public void setCmpdt(String cmpdt) {
		this.cmpdt = cmpdt;
	}

	/**
	 * @return SO..xd_c01.costdt 
	 */
	public String getCostdt() {
		return costdt;
	}

	/**
	 * @param costdt SO..xd_c01.costdt 
	 */
	public void setCostdt(String costdt) {
		this.costdt = costdt;
	}

	/**
	 * @return SO..xd_c01.costis 
	 */
	public String getCostis() {
		return costis;
	}

	/**
	 * @param costis SO..xd_c01.costis 
	 */
	public void setCostis(String costis) {
		this.costis = costis;
	}

	/**
	 * @return SO..xd_c01.costtm 
	 */
	public String getCosttm() {
		return costtm;
	}

	/**
	 * @param costtm SO..xd_c01.costtm 
	 */
	public void setCosttm(String costtm) {
		this.costtm = costtm;
	}

	/**
	 * @return SO..xd_c01.crmid 
	 */
	public String getCrmid() {
		return crmid;
	}

	/**
	 * @param crmid SO..xd_c01.crmid 
	 */
	public void setCrmid(String crmid) {
		this.crmid = crmid;
	}

	/**
	 * @return SO..xd_c01.crmis 
	 */
	public String getCrmis() {
		return crmis;
	}

	/**
	 * @param crmis SO..xd_c01.crmis 
	 */
	public void setCrmis(String crmis) {
		this.crmis = crmis;
	}

	/**
	 * @return SO..xd_c01.crmno 
	 */
	public String getCrmno() {
		return crmno;
	}

	/**
	 * @param crmno SO..xd_c01.crmno 
	 */
	public void setCrmno(String crmno) {
		this.crmno = crmno;
	}

	/**
	 * @return SO..xd_c01.crmyy 
	 */
	public String getCrmyy() {
		return crmyy;
	}

	/**
	 * @param crmyy SO..xd_c01.crmyy 
	 */
	public void setCrmyy(String crmyy) {
		this.crmyy = crmyy;
	}

	/**
	 * @return SO..xd_c01.dpt 
	 */
	public String getDpt() {
		return dpt;
	}

	/**
	 * @param dpt SO..xd_c01.dpt 
	 */
	public void setDpt(String dpt) {
		this.dpt = dpt;
	}

	/**
	 * @return SO..xd_c01.dptcd 
	 */
	public String getDptcd() {
		return dptcd;
	}

	/**
	 * @param dptcd SO..xd_c01.dptcd 
	 */
	public void setDptcd(String dptcd) {
		this.dptcd = dptcd;
	}

	/**
	 * @return SO..xd_c01.dptdt 
	 */
	public String getDptdt() {
		return dptdt;
	}

	/**
	 * @param dptdt SO..xd_c01.dptdt 
	 */
	public void setDptdt(String dptdt) {
		this.dptdt = dptdt;
	}

	/**
	 * @return SO..xd_c01.dptis 
	 */
	public String getDptis() {
		return dptis;
	}

	/**
	 * @param dptis SO..xd_c01.dptis 
	 */
	public void setDptis(String dptis) {
		this.dptis = dptis;
	}

	/**
	 * @return SO..xd_c01.epid 
	 */
	public String getEpid() {
		return epid;
	}

	/**
	 * @param epid SO..xd_c01.epid 
	 */
	public void setEpid(String epid) {
		this.epid = epid;
	}

	/**
	 * @return SO..xd_c01.epno 
	 */
	public String getEpno() {
		return epno;
	}

	/**
	 * @param epno SO..xd_c01.epno 
	 */
	public void setEpno(String epno) {
		this.epno = epno;
	}

	/**
	 * @return SO..xd_c01.epyy 
	 */
	public String getEpyy() {
		return epyy;
	}

	/**
	 * @param epyy SO..xd_c01.epyy 
	 */
	public void setEpyy(String epyy) {
		this.epyy = epyy;
	}

	/**
	 * @return SO..xd_c01.orcrt 
	 */
	public String getOrcrt() {
		return orcrt;
	}

	/**
	 * @param orcrt SO..xd_c01.orcrt 
	 */
	public void setOrcrt(String orcrt) {
		this.orcrt = orcrt;
	}

	/**
	 * @return SO..xd_c01.orcrtid 
	 */
	public String getOrcrtid() {
		return orcrtid;
	}

	/**
	 * @param orcrtid SO..xd_c01.orcrtid 
	 */
	public void setOrcrtid(String orcrtid) {
		this.orcrtid = orcrtid;
	}

	/**
	 * @return SO..xd_c01.rcvdt 
	 */
	public String getRcvdt() {
		return rcvdt;
	}

	/**
	 * @param rcvdt SO..xd_c01.rcvdt 
	 */
	public void setRcvdt(String rcvdt) {
		this.rcvdt = rcvdt;
	}

	/**
	 * @return SO..xd_c01.rcvid 
	 */
	public String getRcvid() {
		return rcvid;
	}

	/**
	 * @param rcvid SO..xd_c01.rcvid 
	 */
	public void setRcvid(String rcvid) {
		this.rcvid = rcvid;
	}

	/**
	 * @return SO..xd_c01.rcvis 
	 */
	public String getRcvis() {
		return rcvis;
	}

	/**
	 * @param rcvis SO..xd_c01.rcvis 
	 */
	public void setRcvis(String rcvis) {
		this.rcvis = rcvis;
	}

	/**
	 * @return SO..xd_c01.rcvno 
	 */
	public String getRcvno() {
		return rcvno;
	}

	/**
	 * @param rcvno SO..xd_c01.rcvno 
	 */
	public void setRcvno(String rcvno) {
		this.rcvno = rcvno;
	}

	/**
	 * @return SO..xd_c01.rcvtm 
	 */
	public String getRcvtm() {
		return rcvtm;
	}

	/**
	 * @param rcvtm SO..xd_c01.rcvtm 
	 */
	public void setRcvtm(String rcvtm) {
		this.rcvtm = rcvtm;
	}

	/**
	 * @return SO..xd_c01.rcvyy 
	 */
	public String getRcvyy() {
		return rcvyy;
	}

	/**
	 * @param rcvyy SO..xd_c01.rcvyy 
	 */
	public void setRcvyy(String rcvyy) {
		this.rcvyy = rcvyy;
	}

	/**
	 * @return SO..xd_c01.rsn 
	 */
	public String getRsn() {
		return rsn;
	}

	/**
	 * @param rsn SO..xd_c01.rsn 
	 */
	public void setRsn(String rsn) {
		this.rsn = rsn;
	}

	/**
	 * @return SO..xd_c01.spcArea 
	 */
	public String getSpcarea() {
		return spcarea;
	}

	/**
	 * @param spcarea SO..xd_c01.spcArea 
	 */
	public void setSpcarea(String spcarea) {
		this.spcarea = spcarea;
	}

	/**
	 * @return SO..xd_c01.spcCity 
	 */
	public String getSpccity() {
		return spccity;
	}

	/**
	 * @param spccity SO..xd_c01.spcCity 
	 */
	public void setSpccity(String spccity) {
		this.spccity = spccity;
	}

	/**
	 * @return SO..xd_c01.spcOrcrt 
	 */
	public String getSpcorcrt() {
		return spcorcrt;
	}

	/**
	 * @param spcorcrt SO..xd_c01.spcOrcrt 
	 */
	public void setSpcorcrt(String spcorcrt) {
		this.spcorcrt = spcorcrt;
	}

	/**
	 * @return SO..xd_c01.spcOrcrtid 
	 */
	public String getSpcorcrtid() {
		return spcorcrtid;
	}

	/**
	 * @param spcorcrtid SO..xd_c01.spcOrcrtid 
	 */
	public void setSpcorcrtid(String spcorcrtid) {
		this.spcorcrtid = spcorcrtid;
	}

	/**
	 * @return SO..xd_c01.spc_area 
	 */
	public String getSpc_area() {
		return spc_area;
	}

	/**
	 * @param spc_area SO..xd_c01.spc_area 
	 */
	public void setSpc_area(String spc_area) {
		this.spc_area = spc_area;
	}

	/**
	 * @return SO..xd_c01.spc_city 
	 */
	public String getSpc_city() {
		return spc_city;
	}

	/**
	 * @param spc_city SO..xd_c01.spc_city 
	 */
	public void setSpc_city(String spc_city) {
		this.spc_city = spc_city;
	}

	/**
	 * @return SO..xd_c01.spc_orcrt 
	 */
	public String getSpc_orcrt() {
		return spc_orcrt;
	}

	/**
	 * @param spc_orcrt SO..xd_c01.spc_orcrt 
	 */
	public void setSpc_orcrt(String spc_orcrt) {
		this.spc_orcrt = spc_orcrt;
	}

	/**
	 * @return SO..xd_c01.spc_orcrtid 
	 */
	public String getSpc_orcrtid() {
		return spc_orcrtid;
	}

	/**
	 * @param spc_orcrtid SO..xd_c01.spc_orcrtid 
	 */
	public void setSpc_orcrtid(String spc_orcrtid) {
		this.spc_orcrtid = spc_orcrtid;
	}

	/**
	 * @return SO..xd_c01.spcis 
	 */
	public String getSpcis() {
		return spcis;
	}

	/**
	 * @param spcis SO..xd_c01.spcis 
	 */
	public void setSpcis(String spcis) {
		this.spcis = spcis;
	}

	/**
	 * @return SO..xd_c01.sys 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..xd_c01.sys 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..xd_c01.uiddt 
	 */
	public String getUiddt() {
		return uiddt;
	}

	/**
	 * @param uiddt SO..xd_c01.uiddt 
	 */
	public void setUiddt(String uiddt) {
		this.uiddt = uiddt;
	}

	/**
	 * @return SO..xd_c01.uidtm 
	 */
	public String getUidtm() {
		return uidtm;
	}

	/**
	 * @param uidtm SO..xd_c01.uidtm 
	 */
	public void setUidtm(String uidtm) {
		this.uidtm = uidtm;
	}

	/**
	 * @return SO..xd_c01.updt 
	 */
	public String getUpdt() {
		return updt;
	}

	/**
	 * @param updt SO..xd_c01.updt 
	 */
	public void setUpdt(String updt) {
		this.updt = updt;
	}

	/**
	 * @return SO..xd_c01.upis 
	 */
	public String getUpis() {
		return upis;
	}

	/**
	 * @param upis SO..xd_c01.upis 
	 */
	public void setUpis(String upis) {
		this.upis = upis;
	}

	/**
	 * @return SO..xd_c01.uptm 
	 */
	public String getUptm() {
		return uptm;
	}

	/**
	 * @param uptm SO..xd_c01.uptm 
	 */
	public void setUptm(String uptm) {
		this.uptm = uptm;
	}

	/**
	 * @return SO..xd_c01.usrid 
	 */
	public String getUsrid() {
		return usrid;
	}

	/**
	 * @param usrid SO..xd_c01.usrid 
	 */
	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

}
