package com.sertek.table;

/**
 * SO..xd_trnlt <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.425<br>
 * 
 */
public class xd_trnlt extends BaseTable {

	/**
	 * SO..xd_trnlt.ftpxmlnm 
	 */
	private String ftpxmlnm = "";

	/**
	 * SO..xd_trnlt.barcode1 
	 */
	private String barcode1 = "";

	/**
	 * SO..xd_trnlt.barcode2 
	 */
	private String barcode2 = "";

	/**
	 * SO..xd_trnlt.barcode3 
	 */
	private String barcode3 = "";

	/**
	 * SO..xd_trnlt.cllbr 
	 */
	private String cllbr = "";

	/**
	 * SO..xd_trnlt.cname 
	 */
	private String cname = "";

	/**
	 * SO..xd_trnlt.code 
	 */
	private String code = "";

	/**
	 * SO..xd_trnlt.costchkdt 
	 */
	private String costchkdt = "";

	/**
	 * SO..xd_trnlt.costdline 
	 */
	private String costdline = "";

	/**
	 * SO..xd_trnlt.costis 
	 */
	private String costis = "";

	/**
	 * SO..xd_trnlt.costtype 
	 */
	private String costtype = "";

	/**
	 * SO..xd_trnlt.curamt 
	 */
	private String curamt = "";

	/**
	 * SO..xd_trnlt.epid 
	 */
	private String epid = "";

	/**
	 * SO..xd_trnlt.epno 
	 */
	private String epno = "";

	/**
	 * SO..xd_trnlt.epyy 
	 */
	private String epyy = "";

	/**
	 * SO..xd_trnlt.orcrt 
	 */
	private String orcrt = "";

	/**
	 * SO..xd_trnlt.orcrtid 
	 */
	private String orcrtid = "";

	/**
	 * SO..xd_trnlt.pname 
	 */
	private String pname = "";

	/**
	 * SO..xd_trnlt.pnameid 
	 */
	private String pnameid = "";

	/**
	 * SO..xd_trnlt.rcpid 
	 */
	private String rcpid = "";

	/**
	 * SO..xd_trnlt.rcpno 
	 */
	private String rcpno = "";

	/**
	 * SO..xd_trnlt.rcptid 
	 */
	private String rcptid = "";

	/**
	 * SO..xd_trnlt.rcpyy 
	 */
	private String rcpyy = "";

	/**
	 * SO..xd_trnlt.rcvbranch 
	 */
	private String rcvbranch = "";

	/**
	 * SO..xd_trnlt.rcvitem 
	 */
	private String rcvitem = "";

	/**
	 * SO..xd_trnlt.rcvmarket 
	 */
	private String rcvmarket = "";

	/**
	 * SO..xd_trnlt.sitdate 
	 */
	private String sitdate = "";

	/**
	 * SO..xd_trnlt.trndt 
	 */
	private String trndt = "";

	/**
	 * SO..xd_trnlt.trntime 
	 */
	private String trntime = "";

	/**
	 * SO..xd_trnlt.trntype 
	 */
	private String trntype = "";

	/**
	 * SO..xd_trnlt.userdata 
	 */
	private String userdata = "";

	/**
	 * SO..xd_trnlt.xptdcnt 
	 */
	private String xptdcnt = "";

	/**
	 * @return SO..xd_trnlt.ftpxmlnm 
	 */
	public String getFtpxmlnm() {
		return ftpxmlnm;
	}

	/**
	 * @param ftpxmlnm SO..xd_trnlt.ftpxmlnm 
	 */
	public void setFtpxmlnm(String ftpxmlnm) {
		this.ftpxmlnm = ftpxmlnm;
	}

	/**
	 * @return SO..xd_trnlt.barcode1 
	 */
	public String getBarcode1() {
		return barcode1;
	}

	/**
	 * @param barcode1 SO..xd_trnlt.barcode1 
	 */
	public void setBarcode1(String barcode1) {
		this.barcode1 = barcode1;
	}

	/**
	 * @return SO..xd_trnlt.barcode2 
	 */
	public String getBarcode2() {
		return barcode2;
	}

	/**
	 * @param barcode2 SO..xd_trnlt.barcode2 
	 */
	public void setBarcode2(String barcode2) {
		this.barcode2 = barcode2;
	}

	/**
	 * @return SO..xd_trnlt.barcode3 
	 */
	public String getBarcode3() {
		return barcode3;
	}

	/**
	 * @param barcode3 SO..xd_trnlt.barcode3 
	 */
	public void setBarcode3(String barcode3) {
		this.barcode3 = barcode3;
	}

	/**
	 * @return SO..xd_trnlt.cllbr 
	 */
	public String getCllbr() {
		return cllbr;
	}

	/**
	 * @param cllbr SO..xd_trnlt.cllbr 
	 */
	public void setCllbr(String cllbr) {
		this.cllbr = cllbr;
	}

	/**
	 * @return SO..xd_trnlt.cname 
	 */
	public String getCname() {
		return cname;
	}

	/**
	 * @param cname SO..xd_trnlt.cname 
	 */
	public void setCname(String cname) {
		this.cname = cname;
	}

	/**
	 * @return SO..xd_trnlt.code 
	 */
	public String getCode() {
		return code;
	}

	/**
	 * @param code SO..xd_trnlt.code 
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * @return SO..xd_trnlt.costchkdt 
	 */
	public String getCostchkdt() {
		return costchkdt;
	}

	/**
	 * @param costchkdt SO..xd_trnlt.costchkdt 
	 */
	public void setCostchkdt(String costchkdt) {
		this.costchkdt = costchkdt;
	}

	/**
	 * @return SO..xd_trnlt.costdline 
	 */
	public String getCostdline() {
		return costdline;
	}

	/**
	 * @param costdline SO..xd_trnlt.costdline 
	 */
	public void setCostdline(String costdline) {
		this.costdline = costdline;
	}

	/**
	 * @return SO..xd_trnlt.costis 
	 */
	public String getCostis() {
		return costis;
	}

	/**
	 * @param costis SO..xd_trnlt.costis 
	 */
	public void setCostis(String costis) {
		this.costis = costis;
	}

	/**
	 * @return SO..xd_trnlt.costtype 
	 */
	public String getCosttype() {
		return costtype;
	}

	/**
	 * @param costtype SO..xd_trnlt.costtype 
	 */
	public void setCosttype(String costtype) {
		this.costtype = costtype;
	}

	/**
	 * @return SO..xd_trnlt.curamt 
	 */
	public String getCuramt() {
		return curamt;
	}

	/**
	 * @param curamt SO..xd_trnlt.curamt 
	 */
	public void setCuramt(String curamt) {
		this.curamt = curamt;
	}

	/**
	 * @return SO..xd_trnlt.epid 
	 */
	public String getEpid() {
		return epid;
	}

	/**
	 * @param epid SO..xd_trnlt.epid 
	 */
	public void setEpid(String epid) {
		this.epid = epid;
	}

	/**
	 * @return SO..xd_trnlt.epno 
	 */
	public String getEpno() {
		return epno;
	}

	/**
	 * @param epno SO..xd_trnlt.epno 
	 */
	public void setEpno(String epno) {
		this.epno = epno;
	}

	/**
	 * @return SO..xd_trnlt.epyy 
	 */
	public String getEpyy() {
		return epyy;
	}

	/**
	 * @param epyy SO..xd_trnlt.epyy 
	 */
	public void setEpyy(String epyy) {
		this.epyy = epyy;
	}

	/**
	 * @return SO..xd_trnlt.orcrt 
	 */
	public String getOrcrt() {
		return orcrt;
	}

	/**
	 * @param orcrt SO..xd_trnlt.orcrt 
	 */
	public void setOrcrt(String orcrt) {
		this.orcrt = orcrt;
	}

	/**
	 * @return SO..xd_trnlt.orcrtid 
	 */
	public String getOrcrtid() {
		return orcrtid;
	}

	/**
	 * @param orcrtid SO..xd_trnlt.orcrtid 
	 */
	public void setOrcrtid(String orcrtid) {
		this.orcrtid = orcrtid;
	}

	/**
	 * @return SO..xd_trnlt.pname 
	 */
	public String getPname() {
		return pname;
	}

	/**
	 * @param pname SO..xd_trnlt.pname 
	 */
	public void setPname(String pname) {
		this.pname = pname;
	}

	/**
	 * @return SO..xd_trnlt.pnameid 
	 */
	public String getPnameid() {
		return pnameid;
	}

	/**
	 * @param pnameid SO..xd_trnlt.pnameid 
	 */
	public void setPnameid(String pnameid) {
		this.pnameid = pnameid;
	}

	/**
	 * @return SO..xd_trnlt.rcpid 
	 */
	public String getRcpid() {
		return rcpid;
	}

	/**
	 * @param rcpid SO..xd_trnlt.rcpid 
	 */
	public void setRcpid(String rcpid) {
		this.rcpid = rcpid;
	}

	/**
	 * @return SO..xd_trnlt.rcpno 
	 */
	public String getRcpno() {
		return rcpno;
	}

	/**
	 * @param rcpno SO..xd_trnlt.rcpno 
	 */
	public void setRcpno(String rcpno) {
		this.rcpno = rcpno;
	}

	/**
	 * @return SO..xd_trnlt.rcptid 
	 */
	public String getRcptid() {
		return rcptid.indexOf("00")==0 ? rcptid.substring(2) : rcptid;
	}

	/**
	 * @param rcptid SO..xd_trnlt.rcptid 
	 */
	public void setRcptid(String rcptid) {
		this.rcptid = rcptid;
	}

	/**
	 * @return SO..xd_trnlt.rcpyy 
	 */
	public String getRcpyy() {
		return rcpyy;
	}

	/**
	 * @param rcpyy SO..xd_trnlt.rcpyy 
	 */
	public void setRcpyy(String rcpyy) {
		this.rcpyy = rcpyy;
	}

	/**
	 * @return SO..xd_trnlt.rcvbranch 
	 */
	public String getRcvbranch() {
		return rcvbranch;
	}

	/**
	 * @param rcvbranch SO..xd_trnlt.rcvbranch 
	 */
	public void setRcvbranch(String rcvbranch) {
		this.rcvbranch = rcvbranch;
	}

	/**
	 * @return SO..xd_trnlt.rcvitem 
	 */
	public String getRcvitem() {
		return rcvitem;
	}

	/**
	 * @param rcvitem SO..xd_trnlt.rcvitem 
	 */
	public void setRcvitem(String rcvitem) {
		this.rcvitem = rcvitem;
	}

	/**
	 * @return SO..xd_trnlt.rcvmarket 
	 */
	public String getRcvmarket() {
		return rcvmarket;
	}

	/**
	 * @param rcvmarket SO..xd_trnlt.rcvmarket 
	 */
	public void setRcvmarket(String rcvmarket) {
		this.rcvmarket = rcvmarket;
	}

	/**
	 * @return SO..xd_trnlt.sitdate 
	 */
	public String getSitdate() {
		return sitdate;
	}

	/**
	 * @param sitdate SO..xd_trnlt.sitdate 
	 */
	public void setSitdate(String sitdate) {
		this.sitdate = sitdate;
	}

	/**
	 * @return SO..xd_trnlt.trndt 
	 */
	public String getTrndt() {
		return trndt;
	}

	/**
	 * @param trndt SO..xd_trnlt.trndt 
	 */
	public void setTrndt(String trndt) {
		this.trndt = trndt;
	}

	/**
	 * @return SO..xd_trnlt.trntime 
	 */
	public String getTrntime() {
		return trntime;
	}

	/**
	 * @param trntime SO..xd_trnlt.trntime 
	 */
	public void setTrntime(String trntime) {
		this.trntime = trntime;
	}

	/**
	 * @return SO..xd_trnlt.trntype 
	 */
	public String getTrntype() {
		return trntype;
	}

	/**
	 * @param trntype SO..xd_trnlt.trntype 
	 */
	public void setTrntype(String trntype) {
		this.trntype = trntype;
	}

	/**
	 * @return SO..xd_trnlt.userdata 
	 */
	public String getUserdata() {
		return userdata;
	}

	/**
	 * @param userdata SO..xd_trnlt.userdata 
	 */
	public void setUserdata(String userdata) {
		this.userdata = userdata;
	}

	/**
	 * @return SO..xd_trnlt.xptdcnt 
	 */
	public String getXptdcnt() {
		return xptdcnt;
	}

	/**
	 * @param xptdcnt SO..xd_trnlt.xptdcnt 
	 */
	public void setXptdcnt(String xptdcnt) {
		this.xptdcnt = xptdcnt;
	}

}
