package com.sertek.table;

/**
 * SO..Y60_bak <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.503<br>
 * 
 */
public class Y60_bak extends BaseTable {

	/**
	 * SO..Y60_bak.INSDT 
	 */
	private String insdt = "";

	/**
	 * SO..Y60_bak.INSTM 
	 */
	private String instm = "";

	/**
	 * SO..Y60_bak.INSSEQ 
	 */
	private String insseq = "";

	/**
	 * SO..Y60_bak.DOC_NO 
	 */
	private String doc_no = "";

	/**
	 * SO..Y60_bak.SYS 
	 */
	private String sys = "";

	/**
	 * SO..Y60_bak.RCVYY 
	 */
	private String rcvyy = "";

	/**
	 * SO..Y60_bak.RCVID 
	 */
	private String rcvid = "";

	/**
	 * SO..Y60_bak.RCVNO 
	 */
	private String rcvno = "";

	/**
	 * SO..Y60_bak.CRMYY 
	 */
	private String crmyy = "";

	/**
	 * SO..Y60_bak.CRMID 
	 */
	private String crmid = "";

	/**
	 * SO..Y60_bak.CRMNO 
	 */
	private String crmno = "";

	/**
	 * SO..Y60_bak.DPT 
	 */
	private String dpt = "";

	/**
	 * SO..Y60_bak.RSN 
	 */
	private String rsn = "";

	/**
	 * SO..Y60_bak.CRMDT 
	 */
	private String crmdt = "";

	/**
	 * SO..Y60_bak.PEDT 
	 */
	private String pedt = "";

	/**
	 * SO..Y60_bak.RCVDT 
	 */
	private String rcvdt = "";

	/**
	 * SO..Y60_bak.RCVTM 
	 */
	private String rcvtm = "";

	/**
	 * SO..Y60_bak.CRTID 
	 */
	private String crtid = "";

	/**
	 * @return SO..Y60_bak.INSDT 
	 */
	public String getInsdt() {
		return insdt;
	}

	/**
	 * @param insdt SO..Y60_bak.INSDT 
	 */
	public void setInsdt(String insdt) {
		this.insdt = insdt;
	}

	/**
	 * @return SO..Y60_bak.INSTM 
	 */
	public String getInstm() {
		return instm;
	}

	/**
	 * @param instm SO..Y60_bak.INSTM 
	 */
	public void setInstm(String instm) {
		this.instm = instm;
	}

	/**
	 * @return SO..Y60_bak.INSSEQ 
	 */
	public String getInsseq() {
		return insseq;
	}

	/**
	 * @param insseq SO..Y60_bak.INSSEQ 
	 */
	public void setInsseq(String insseq) {
		this.insseq = insseq;
	}

	/**
	 * @return SO..Y60_bak.DOC_NO 
	 */
	public String getDoc_no() {
		return doc_no;
	}

	/**
	 * @param doc_no SO..Y60_bak.DOC_NO 
	 */
	public void setDoc_no(String doc_no) {
		this.doc_no = doc_no;
	}

	/**
	 * @return SO..Y60_bak.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..Y60_bak.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..Y60_bak.RCVYY 
	 */
	public String getRcvyy() {
		return rcvyy;
	}

	/**
	 * @param rcvyy SO..Y60_bak.RCVYY 
	 */
	public void setRcvyy(String rcvyy) {
		this.rcvyy = rcvyy;
	}

	/**
	 * @return SO..Y60_bak.RCVID 
	 */
	public String getRcvid() {
		return rcvid;
	}

	/**
	 * @param rcvid SO..Y60_bak.RCVID 
	 */
	public void setRcvid(String rcvid) {
		this.rcvid = rcvid;
	}

	/**
	 * @return SO..Y60_bak.RCVNO 
	 */
	public String getRcvno() {
		return rcvno;
	}

	/**
	 * @param rcvno SO..Y60_bak.RCVNO 
	 */
	public void setRcvno(String rcvno) {
		this.rcvno = rcvno;
	}

	/**
	 * @return SO..Y60_bak.CRMYY 
	 */
	public String getCrmyy() {
		return crmyy;
	}

	/**
	 * @param crmyy SO..Y60_bak.CRMYY 
	 */
	public void setCrmyy(String crmyy) {
		this.crmyy = crmyy;
	}

	/**
	 * @return SO..Y60_bak.CRMID 
	 */
	public String getCrmid() {
		return crmid;
	}

	/**
	 * @param crmid SO..Y60_bak.CRMID 
	 */
	public void setCrmid(String crmid) {
		this.crmid = crmid;
	}

	/**
	 * @return SO..Y60_bak.CRMNO 
	 */
	public String getCrmno() {
		return crmno;
	}

	/**
	 * @param crmno SO..Y60_bak.CRMNO 
	 */
	public void setCrmno(String crmno) {
		this.crmno = crmno;
	}

	/**
	 * @return SO..Y60_bak.DPT 
	 */
	public String getDpt() {
		return dpt;
	}

	/**
	 * @param dpt SO..Y60_bak.DPT 
	 */
	public void setDpt(String dpt) {
		this.dpt = dpt;
	}

	/**
	 * @return SO..Y60_bak.RSN 
	 */
	public String getRsn() {
		return rsn;
	}

	/**
	 * @param rsn SO..Y60_bak.RSN 
	 */
	public void setRsn(String rsn) {
		this.rsn = rsn;
	}

	/**
	 * @return SO..Y60_bak.CRMDT 
	 */
	public String getCrmdt() {
		return crmdt;
	}

	/**
	 * @param crmdt SO..Y60_bak.CRMDT 
	 */
	public void setCrmdt(String crmdt) {
		this.crmdt = crmdt;
	}

	/**
	 * @return SO..Y60_bak.PEDT 
	 */
	public String getPedt() {
		return pedt;
	}

	/**
	 * @param pedt SO..Y60_bak.PEDT 
	 */
	public void setPedt(String pedt) {
		this.pedt = pedt;
	}

	/**
	 * @return SO..Y60_bak.RCVDT 
	 */
	public String getRcvdt() {
		return rcvdt;
	}

	/**
	 * @param rcvdt SO..Y60_bak.RCVDT 
	 */
	public void setRcvdt(String rcvdt) {
		this.rcvdt = rcvdt;
	}

	/**
	 * @return SO..Y60_bak.RCVTM 
	 */
	public String getRcvtm() {
		return rcvtm;
	}

	/**
	 * @param rcvtm SO..Y60_bak.RCVTM 
	 */
	public void setRcvtm(String rcvtm) {
		this.rcvtm = rcvtm;
	}

	/**
	 * @return SO..Y60_bak.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..Y60_bak.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

}
