package com.sertek.table;

/**
 * SO..Y62_bak <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.645<br>
 * 
 */
public class Y62_bak extends BaseTable {

	/**
	 * SO..Y62_bak.DOC_NO 
	 */
	private String doc_no = "";

	/**
	 * SO..Y62_bak.INSDT 
	 */
	private String insdt = "";

	/**
	 * SO..Y62_bak.INSTM 
	 */
	private String instm = "";

	/**
	 * SO..Y62_bak.INSSEQ 
	 */
	private String insseq = "";

	/**
	 * SO..Y62_bak.SYS 
	 */
	private String sys = "";

	/**
	 * SO..Y62_bak.RCVYY 
	 */
	private String rcvyy = "";

	/**
	 * SO..Y62_bak.RCVID 
	 */
	private String rcvid = "";

	/**
	 * SO..Y62_bak.RCVNO 
	 */
	private String rcvno = "";

	/**
	 * SO..Y62_bak.CRMYY 
	 */
	private String crmyy = "";

	/**
	 * SO..Y62_bak.CRMID 
	 */
	private String crmid = "";

	/**
	 * SO..Y62_bak.CRMNO 
	 */
	private String crmno = "";

	/**
	 * SO..Y62_bak.SYSID 
	 */
	private String sysid = "";

	/**
	 * SO..Y62_bak.DAKD 
	 */
	private String dakd = "";

	/**
	 * SO..Y62_bak.ZIP 
	 */
	private String zip = "";

	/**
	 * SO..Y62_bak.AD 
	 */
	private String ad = "";

	/**
	 * SO..Y62_bak.CRTID 
	 */
	private String crtid = "";

	/**
	 * @return SO..Y62_bak.DOC_NO 
	 */
	public String getDoc_no() {
		return doc_no;
	}

	/**
	 * @param doc_no SO..Y62_bak.DOC_NO 
	 */
	public void setDoc_no(String doc_no) {
		this.doc_no = doc_no;
	}

	/**
	 * @return SO..Y62_bak.INSDT 
	 */
	public String getInsdt() {
		return insdt;
	}

	/**
	 * @param insdt SO..Y62_bak.INSDT 
	 */
	public void setInsdt(String insdt) {
		this.insdt = insdt;
	}

	/**
	 * @return SO..Y62_bak.INSTM 
	 */
	public String getInstm() {
		return instm;
	}

	/**
	 * @param instm SO..Y62_bak.INSTM 
	 */
	public void setInstm(String instm) {
		this.instm = instm;
	}

	/**
	 * @return SO..Y62_bak.INSSEQ 
	 */
	public String getInsseq() {
		return insseq;
	}

	/**
	 * @param insseq SO..Y62_bak.INSSEQ 
	 */
	public void setInsseq(String insseq) {
		this.insseq = insseq;
	}

	/**
	 * @return SO..Y62_bak.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..Y62_bak.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..Y62_bak.RCVYY 
	 */
	public String getRcvyy() {
		return rcvyy;
	}

	/**
	 * @param rcvyy SO..Y62_bak.RCVYY 
	 */
	public void setRcvyy(String rcvyy) {
		this.rcvyy = rcvyy;
	}

	/**
	 * @return SO..Y62_bak.RCVID 
	 */
	public String getRcvid() {
		return rcvid;
	}

	/**
	 * @param rcvid SO..Y62_bak.RCVID 
	 */
	public void setRcvid(String rcvid) {
		this.rcvid = rcvid;
	}

	/**
	 * @return SO..Y62_bak.RCVNO 
	 */
	public String getRcvno() {
		return rcvno;
	}

	/**
	 * @param rcvno SO..Y62_bak.RCVNO 
	 */
	public void setRcvno(String rcvno) {
		this.rcvno = rcvno;
	}

	/**
	 * @return SO..Y62_bak.CRMYY 
	 */
	public String getCrmyy() {
		return crmyy;
	}

	/**
	 * @param crmyy SO..Y62_bak.CRMYY 
	 */
	public void setCrmyy(String crmyy) {
		this.crmyy = crmyy;
	}

	/**
	 * @return SO..Y62_bak.CRMID 
	 */
	public String getCrmid() {
		return crmid;
	}

	/**
	 * @param crmid SO..Y62_bak.CRMID 
	 */
	public void setCrmid(String crmid) {
		this.crmid = crmid;
	}

	/**
	 * @return SO..Y62_bak.CRMNO 
	 */
	public String getCrmno() {
		return crmno;
	}

	/**
	 * @param crmno SO..Y62_bak.CRMNO 
	 */
	public void setCrmno(String crmno) {
		this.crmno = crmno;
	}

	/**
	 * @return SO..Y62_bak.SYSID 
	 */
	public String getSysid() {
		return sysid;
	}

	/**
	 * @param sysid SO..Y62_bak.SYSID 
	 */
	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	/**
	 * @return SO..Y62_bak.DAKD 
	 */
	public String getDakd() {
		return dakd;
	}

	/**
	 * @param dakd SO..Y62_bak.DAKD 
	 */
	public void setDakd(String dakd) {
		this.dakd = dakd;
	}

	/**
	 * @return SO..Y62_bak.ZIP 
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * @param zip SO..Y62_bak.ZIP 
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * @return SO..Y62_bak.AD 
	 */
	public String getAd() {
		return ad;
	}

	/**
	 * @param ad SO..Y62_bak.AD 
	 */
	public void setAd(String ad) {
		this.ad = ad;
	}

	/**
	 * @return SO..Y62_bak.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..Y62_bak.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

}
