package com.sertek.table;

/**
 * SO..Y6A_bak <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.693<br>
 * 
 */
public class Y6A_bak extends BaseTable {

	/**
	 * SO..Y6A_bak.DOC_NO 
	 */
	private String doc_no = "";

	/**
	 * SO..Y6A_bak.INSDT 
	 */
	private String insdt = "";

	/**
	 * SO..Y6A_bak.INSTM 
	 */
	private String instm = "";

	/**
	 * SO..Y6A_bak.INSSEQ 
	 */
	private String insseq = "";

	/**
	 * SO..Y6A_bak.USRID 
	 */
	private String usrid = "";

	/**
	 * SO..Y6A_bak.YESREAD 
	 */
	private String yesread = "";

	/**
	 * SO..Y6A_bak.SYS 
	 */
	private String sys = "";

	/**
	 * SO..Y6A_bak.RCVYY 
	 */
	private String rcvyy = "";

	/**
	 * SO..Y6A_bak.RCVID 
	 */
	private String rcvid = "";

	/**
	 * SO..Y6A_bak.RCVNO 
	 */
	private String rcvno = "";

	/**
	 * SO..Y6A_bak.CRMYY 
	 */
	private String crmyy = "";

	/**
	 * SO..Y6A_bak.CRMID 
	 */
	private String crmid = "";

	/**
	 * SO..Y6A_bak.CRMNO 
	 */
	private String crmno = "";

	/**
	 * SO..Y6A_bak.SYSID 
	 */
	private String sysid = "";

	/**
	 * SO..Y6A_bak.SEQ 
	 */
	private String seq = "";

	/**
	 * SO..Y6A_bak.IDAPT 
	 */
	private String idapt = "";

	/**
	 * SO..Y6A_bak.IDNM 
	 */
	private String idnm = "";

	/**
	 * SO..Y6A_bak.CLNM 
	 */
	private String clnm = "";

	/**
	 * SO..Y6A_bak.IDNO 
	 */
	private String idno = "";

	/**
	 * SO..Y6A_bak.SEX 
	 */
	private String sex = "";

	/**
	 * SO..Y6A_bak.PNTV 
	 */
	private String pntv = "";

	/**
	 * SO..Y6A_bak.DNTV 
	 */
	private String dntv = "";

	/**
	 * SO..Y6A_bak.PFS 
	 */
	private String pfs = "";

	/**
	 * SO..Y6A_bak.TEL 
	 */
	private String tel = "";

	/**
	 * SO..Y6A_bak.DU 
	 */
	private String du = "";

	/**
	 * SO..Y6A_bak.RMK 
	 */
	private String rmk = "";

	/**
	 * SO..Y6A_bak.BIRDT 
	 */
	private String birdt = "";

	/**
	 * SO..Y6A_bak.FUNM 
	 */
	private String funm = "";

	/**
	 * SO..Y6A_bak.MGYN 
	 */
	private String mgyn = "";

	/**
	 * SO..Y6A_bak.OID 
	 */
	private String oid = "";

	/**
	 * SO..Y6A_bak.KINDA 
	 */
	private String kinda = "";

	/**
	 * SO..Y6A_bak.SPID 
	 */
	private String spid = "";

	/**
	 * SO..Y6A_bak.BC 
	 */
	private String bc = "";

	/**
	 * SO..Y6A_bak.CRTID 
	 */
	private String crtid = "";

	/**
	 * @return SO..Y6A_bak.DOC_NO 
	 */
	public String getDoc_no() {
		return doc_no;
	}

	/**
	 * @param doc_no SO..Y6A_bak.DOC_NO 
	 */
	public void setDoc_no(String doc_no) {
		this.doc_no = doc_no;
	}

	/**
	 * @return SO..Y6A_bak.INSDT 
	 */
	public String getInsdt() {
		return insdt;
	}

	/**
	 * @param insdt SO..Y6A_bak.INSDT 
	 */
	public void setInsdt(String insdt) {
		this.insdt = insdt;
	}

	/**
	 * @return SO..Y6A_bak.INSTM 
	 */
	public String getInstm() {
		return instm;
	}

	/**
	 * @param instm SO..Y6A_bak.INSTM 
	 */
	public void setInstm(String instm) {
		this.instm = instm;
	}

	/**
	 * @return SO..Y6A_bak.INSSEQ 
	 */
	public String getInsseq() {
		return insseq;
	}

	/**
	 * @param insseq SO..Y6A_bak.INSSEQ 
	 */
	public void setInsseq(String insseq) {
		this.insseq = insseq;
	}

	/**
	 * @return SO..Y6A_bak.USRID 
	 */
	public String getUsrid() {
		return usrid;
	}

	/**
	 * @param usrid SO..Y6A_bak.USRID 
	 */
	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

	/**
	 * @return SO..Y6A_bak.YESREAD 
	 */
	public String getYesread() {
		return yesread;
	}

	/**
	 * @param yesread SO..Y6A_bak.YESREAD 
	 */
	public void setYesread(String yesread) {
		this.yesread = yesread;
	}

	/**
	 * @return SO..Y6A_bak.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..Y6A_bak.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..Y6A_bak.RCVYY 
	 */
	public String getRcvyy() {
		return rcvyy;
	}

	/**
	 * @param rcvyy SO..Y6A_bak.RCVYY 
	 */
	public void setRcvyy(String rcvyy) {
		this.rcvyy = rcvyy;
	}

	/**
	 * @return SO..Y6A_bak.RCVID 
	 */
	public String getRcvid() {
		return rcvid;
	}

	/**
	 * @param rcvid SO..Y6A_bak.RCVID 
	 */
	public void setRcvid(String rcvid) {
		this.rcvid = rcvid;
	}

	/**
	 * @return SO..Y6A_bak.RCVNO 
	 */
	public String getRcvno() {
		return rcvno;
	}

	/**
	 * @param rcvno SO..Y6A_bak.RCVNO 
	 */
	public void setRcvno(String rcvno) {
		this.rcvno = rcvno;
	}

	/**
	 * @return SO..Y6A_bak.CRMYY 
	 */
	public String getCrmyy() {
		return crmyy;
	}

	/**
	 * @param crmyy SO..Y6A_bak.CRMYY 
	 */
	public void setCrmyy(String crmyy) {
		this.crmyy = crmyy;
	}

	/**
	 * @return SO..Y6A_bak.CRMID 
	 */
	public String getCrmid() {
		return crmid;
	}

	/**
	 * @param crmid SO..Y6A_bak.CRMID 
	 */
	public void setCrmid(String crmid) {
		this.crmid = crmid;
	}

	/**
	 * @return SO..Y6A_bak.CRMNO 
	 */
	public String getCrmno() {
		return crmno;
	}

	/**
	 * @param crmno SO..Y6A_bak.CRMNO 
	 */
	public void setCrmno(String crmno) {
		this.crmno = crmno;
	}

	/**
	 * @return SO..Y6A_bak.SYSID 
	 */
	public String getSysid() {
		return sysid;
	}

	/**
	 * @param sysid SO..Y6A_bak.SYSID 
	 */
	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	/**
	 * @return SO..Y6A_bak.SEQ 
	 */
	public String getSeq() {
		return seq;
	}

	/**
	 * @param seq SO..Y6A_bak.SEQ 
	 */
	public void setSeq(String seq) {
		this.seq = seq;
	}

	/**
	 * @return SO..Y6A_bak.IDAPT 
	 */
	public String getIdapt() {
		return idapt;
	}

	/**
	 * @param idapt SO..Y6A_bak.IDAPT 
	 */
	public void setIdapt(String idapt) {
		this.idapt = idapt;
	}

	/**
	 * @return SO..Y6A_bak.IDNM 
	 */
	public String getIdnm() {
		return idnm;
	}

	/**
	 * @param idnm SO..Y6A_bak.IDNM 
	 */
	public void setIdnm(String idnm) {
		this.idnm = idnm;
	}

	/**
	 * @return SO..Y6A_bak.CLNM 
	 */
	public String getClnm() {
		return clnm;
	}

	/**
	 * @param clnm SO..Y6A_bak.CLNM 
	 */
	public void setClnm(String clnm) {
		this.clnm = clnm;
	}

	/**
	 * @return SO..Y6A_bak.IDNO 
	 */
	public String getIdno() {
		return idno;
	}

	/**
	 * @param idno SO..Y6A_bak.IDNO 
	 */
	public void setIdno(String idno) {
		this.idno = idno;
	}

	/**
	 * @return SO..Y6A_bak.SEX 
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * @param sex SO..Y6A_bak.SEX 
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * @return SO..Y6A_bak.PNTV 
	 */
	public String getPntv() {
		return pntv;
	}

	/**
	 * @param pntv SO..Y6A_bak.PNTV 
	 */
	public void setPntv(String pntv) {
		this.pntv = pntv;
	}

	/**
	 * @return SO..Y6A_bak.DNTV 
	 */
	public String getDntv() {
		return dntv;
	}

	/**
	 * @param dntv SO..Y6A_bak.DNTV 
	 */
	public void setDntv(String dntv) {
		this.dntv = dntv;
	}

	/**
	 * @return SO..Y6A_bak.PFS 
	 */
	public String getPfs() {
		return pfs;
	}

	/**
	 * @param pfs SO..Y6A_bak.PFS 
	 */
	public void setPfs(String pfs) {
		this.pfs = pfs;
	}

	/**
	 * @return SO..Y6A_bak.TEL 
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * @param tel SO..Y6A_bak.TEL 
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * @return SO..Y6A_bak.DU 
	 */
	public String getDu() {
		return du;
	}

	/**
	 * @param du SO..Y6A_bak.DU 
	 */
	public void setDu(String du) {
		this.du = du;
	}

	/**
	 * @return SO..Y6A_bak.RMK 
	 */
	public String getRmk() {
		return rmk;
	}

	/**
	 * @param rmk SO..Y6A_bak.RMK 
	 */
	public void setRmk(String rmk) {
		this.rmk = rmk;
	}

	/**
	 * @return SO..Y6A_bak.BIRDT 
	 */
	public String getBirdt() {
		return birdt;
	}

	/**
	 * @param birdt SO..Y6A_bak.BIRDT 
	 */
	public void setBirdt(String birdt) {
		this.birdt = birdt;
	}

	/**
	 * @return SO..Y6A_bak.FUNM 
	 */
	public String getFunm() {
		return funm;
	}

	/**
	 * @param funm SO..Y6A_bak.FUNM 
	 */
	public void setFunm(String funm) {
		this.funm = funm;
	}

	/**
	 * @return SO..Y6A_bak.MGYN 
	 */
	public String getMgyn() {
		return mgyn;
	}

	/**
	 * @param mgyn SO..Y6A_bak.MGYN 
	 */
	public void setMgyn(String mgyn) {
		this.mgyn = mgyn;
	}

	/**
	 * @return SO..Y6A_bak.OID 
	 */
	public String getOid() {
		return oid;
	}

	/**
	 * @param oid SO..Y6A_bak.OID 
	 */
	public void setOid(String oid) {
		this.oid = oid;
	}

	/**
	 * @return SO..Y6A_bak.KINDA 
	 */
	public String getKinda() {
		return kinda;
	}

	/**
	 * @param kinda SO..Y6A_bak.KINDA 
	 */
	public void setKinda(String kinda) {
		this.kinda = kinda;
	}

	/**
	 * @return SO..Y6A_bak.SPID 
	 */
	public String getSpid() {
		return spid;
	}

	/**
	 * @param spid SO..Y6A_bak.SPID 
	 */
	public void setSpid(String spid) {
		this.spid = spid;
	}

	/**
	 * @return SO..Y6A_bak.BC 
	 */
	public String getBc() {
		return bc;
	}

	/**
	 * @param bc SO..Y6A_bak.BC 
	 */
	public void setBc(String bc) {
		this.bc = bc;
	}

	/**
	 * @return SO..Y6A_bak.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..Y6A_bak.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

}
