package com.sertek.table;

/**
 * SO..Y6B <br>
 * generated by SqlServerIbator on 2014-12-19 10:47:31.693<br>
 * 
 */
public class Y6B extends BaseTable {

	/**
	 * SO..Y6B.DOC_NO 
	 */
	private String doc_no = "";

	/**
	 * SO..Y6B.SYS 
	 */
	private String sys = "";

	/**
	 * SO..Y6B.RCVYY 
	 */
	private String rcvyy = "";

	/**
	 * SO..Y6B.RCVID 
	 */
	private String rcvid = "";

	/**
	 * SO..Y6B.RCVNO 
	 */
	private String rcvno = "";

	/**
	 * SO..Y6B.CRMYY 
	 */
	private String crmyy = "";

	/**
	 * SO..Y6B.CRMID 
	 */
	private String crmid = "";

	/**
	 * SO..Y6B.CRMNO 
	 */
	private String crmno = "";

	/**
	 * SO..Y6B.CLSYSID 
	 */
	private String clsysid = "";

	/**
	 * SO..Y6B.CLIDAPT 
	 */
	private String clidapt = "";

	/**
	 * SO..Y6B.AGSYSID 
	 */
	private String agsysid = "";

	/**
	 * SO..Y6B.AGIDAPT 
	 */
	private String agidapt = "";

	/**
	 * SO..Y6B.CLIDNM 
	 */
	private String clidnm = "";

	/**
	 * SO..Y6B.AGIDNM 
	 */
	private String agidnm = "";

	/**
	 * SO..Y6B.CRTID 
	 */
	private String crtid = "";

	/**
	 * @return SO..Y6B.DOC_NO 
	 */
	public String getDoc_no() {
		return doc_no;
	}

	/**
	 * @param doc_no SO..Y6B.DOC_NO 
	 */
	public void setDoc_no(String doc_no) {
		this.doc_no = doc_no;
	}

	/**
	 * @return SO..Y6B.SYS 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * @param sys SO..Y6B.SYS 
	 */
	public void setSys(String sys) {
		this.sys = sys;
	}

	/**
	 * @return SO..Y6B.RCVYY 
	 */
	public String getRcvyy() {
		return rcvyy;
	}

	/**
	 * @param rcvyy SO..Y6B.RCVYY 
	 */
	public void setRcvyy(String rcvyy) {
		this.rcvyy = rcvyy;
	}

	/**
	 * @return SO..Y6B.RCVID 
	 */
	public String getRcvid() {
		return rcvid;
	}

	/**
	 * @param rcvid SO..Y6B.RCVID 
	 */
	public void setRcvid(String rcvid) {
		this.rcvid = rcvid;
	}

	/**
	 * @return SO..Y6B.RCVNO 
	 */
	public String getRcvno() {
		return rcvno;
	}

	/**
	 * @param rcvno SO..Y6B.RCVNO 
	 */
	public void setRcvno(String rcvno) {
		this.rcvno = rcvno;
	}

	/**
	 * @return SO..Y6B.CRMYY 
	 */
	public String getCrmyy() {
		return crmyy;
	}

	/**
	 * @param crmyy SO..Y6B.CRMYY 
	 */
	public void setCrmyy(String crmyy) {
		this.crmyy = crmyy;
	}

	/**
	 * @return SO..Y6B.CRMID 
	 */
	public String getCrmid() {
		return crmid;
	}

	/**
	 * @param crmid SO..Y6B.CRMID 
	 */
	public void setCrmid(String crmid) {
		this.crmid = crmid;
	}

	/**
	 * @return SO..Y6B.CRMNO 
	 */
	public String getCrmno() {
		return crmno;
	}

	/**
	 * @param crmno SO..Y6B.CRMNO 
	 */
	public void setCrmno(String crmno) {
		this.crmno = crmno;
	}

	/**
	 * @return SO..Y6B.CLSYSID 
	 */
	public String getClsysid() {
		return clsysid;
	}

	/**
	 * @param clsysid SO..Y6B.CLSYSID 
	 */
	public void setClsysid(String clsysid) {
		this.clsysid = clsysid;
	}

	/**
	 * @return SO..Y6B.CLIDAPT 
	 */
	public String getClidapt() {
		return clidapt;
	}

	/**
	 * @param clidapt SO..Y6B.CLIDAPT 
	 */
	public void setClidapt(String clidapt) {
		this.clidapt = clidapt;
	}

	/**
	 * @return SO..Y6B.AGSYSID 
	 */
	public String getAgsysid() {
		return agsysid;
	}

	/**
	 * @param agsysid SO..Y6B.AGSYSID 
	 */
	public void setAgsysid(String agsysid) {
		this.agsysid = agsysid;
	}

	/**
	 * @return SO..Y6B.AGIDAPT 
	 */
	public String getAgidapt() {
		return agidapt;
	}

	/**
	 * @param agidapt SO..Y6B.AGIDAPT 
	 */
	public void setAgidapt(String agidapt) {
		this.agidapt = agidapt;
	}

	/**
	 * @return SO..Y6B.CLIDNM 
	 */
	public String getClidnm() {
		return clidnm;
	}

	/**
	 * @param clidnm SO..Y6B.CLIDNM 
	 */
	public void setClidnm(String clidnm) {
		this.clidnm = clidnm;
	}

	/**
	 * @return SO..Y6B.AGIDNM 
	 */
	public String getAgidnm() {
		return agidnm;
	}

	/**
	 * @param agidnm SO..Y6B.AGIDNM 
	 */
	public void setAgidnm(String agidnm) {
		this.agidnm = agidnm;
	}

	/**
	 * @return SO..Y6B.CRTID 
	 */
	public String getCrtid() {
		return crtid;
	}

	/**
	 * @param crtid SO..Y6B.CRTID 
	 */
	public void setCrtid(String crtid) {
		this.crtid = crtid;
	}

}
